WAFO. Description of holmberg3
Home > wafo > trgauss > private > holmberg3.m
holmberg3
PURPOSE
Computes moments for higher order reliability methods.
SYNOPSIS
E=holmberg3(S,a,b,Q1,Q2,Q3)
DESCRIPTION
  HOLMBERG3 Computes moments for higher order reliability methods.
  CALL: E=holmberg3(S,a,b,Q1,Q2,Q3);
  Computation of the expectation of
  sqrt(pi/2)*(b'*X)*(X'*Q1*X)(X'*Q2*X)*(X'*Q3*X)(2*normcdf(a'*X)-1)
  if S is normally distributed with mean zero and covariance matrix
  S.
CROSS-REFERENCE INFORMATION
This function calls:
holmquist1
Computes moments for higher order reliability methods.
holmquist2
Computes moments for higher order reliability methods.
holmquist3
Computes moments for higher order reliability methods.
This function is called by:
rqlf_asympt
Gives first two terms in an asymptotic expansion of the
SOURCE CODE
01 function E=holmberg3(S,a,b,Q1,Q2,Q3)
02 % HOLMBERG3 Computes moments for higher order reliability methods.
03 %
04 % CALL: E=holmberg3(S,a,b,Q1,Q2,Q3);
05 %
06 % Computation of the expectation of
07 % sqrt(pi/2)*(b'*X)*(X'*Q1*X)(X'*Q2*X)*(X'*Q3*X)(2*normcdf(a'*X)-1)
08 % if S is normally distributed with mean zero and covariance matrix
09 % S.
10 Q1=0.5*(Q1+Q1');
11 Q2=0.5*(Q2+Q2');
12 Q3=0.5*(Q3+Q3');
13
14 E=-1/8*(15*1*(a'*S*b)*(2*a'*(S*Q1*S)*a)*(2*a'*(S*Q2*S)*a)*(2*a'*(S*Q3*S)*a)-6*holmquist1(S,Q1)*(a'*S*b)*(2*a'*(S*Q2*S)*a)*(2*a'*(S*Q3*S)*a)-6*1*(2*a'*(S*Q3*S)*b)*(2*a'*(S*Q1*S)*a)*(2*a'*(S*Q2*S)*a)-6*1*(2*a'*(S*Q2*S)*b)*(2*a'*(S*Q1*S)*a)*(2*a'*(S*Q3*S)*a)-6*holmquist1(S,Q3)*(a'*S*b)*(2*a'*(S*Q1*S)*a)*(2*a'*(S*Q2*S)*a)-6*holmquist1(S,Q2)*(a'*S*b)*(2*a'*(S*Q1*S)*a)*(2*a'*(S*Q3*S)*a)+4*holmquist1(S,Q3)*(2*a'*(S*Q1*S)*b)*(2*a'*(S*Q2*S)*a)+4*holmquist1(S,Q2)*(2*a'*(S*Q1*S)*b)*(2*a'*(S*Q3*S)*a)+4*holmquist1(S,Q1)*(2*a'*(S*Q3*S)*b)*(2*a'*(S*Q2*S)*a)+4*holmquist1(S,Q1)*(2*a'*(S*Q2*S)*b)*(2*a'*(S*Q3*S)*a)+4*holmquist1(S,Q3)*(2*a'*(S*Q2*S)*b)*(2*a'*(S*Q1*S)*a)+4*holmquist1(S,Q2)*(2*a'*(S*Q3*S)*b)*(2*a'*(S*Q1*S)*a)-6*1*(2*a'*(S*Q1*S)*b)*(2*a'*(S*Q2*S)*a)*(2*a'*(S*Q3*S)*a)+4*holmquist1(S,Q3)*(2*a'*(S*Q1*S)*b)*(2*a'*(S*Q2*S)*a)*(a'*S*a)^2+8*holmquist1(S,Q3)*(2*a'*(S*Q1*S)*b)*(2*a'*(S*Q2*S)*a)*(a'*S*a)+4*holmquist1(S,Q2)*(2*a'*(S*Q1*S)*b)*(2*a'*(S*Q3*S)*a)*(a'*S*a)^2+8*holmquist1(S,Q2)*(2*a'*(S*Q1*S)*b)*(2*a'*(S*Q3*S)*a)*(a'*S*a)+4*holmquist1(S,Q1)*(2*a'*(S*Q3*S)*b)*(2*a'*(S*Q2*S)*a)*(a'*S*a)^2+8*holmquist1(S,Q1)*(2*a'*(S*Q3*S)*b)*(2*a'*(S*Q2*S)*a)*(a'*S*a)+4*holmquist1(S,Q1)*(2*a'*(S*Q2*S)*b)*(2*a'*(S*Q3*S)*a)*(a'*S*a)^2+8*holmquist1(S,Q1)*(2*a'*(S*Q2*S)*b)*(2*a'*(S*Q3*S)*a)*(a'*S*a)+4*holmquist1(S,Q3)*(2*a'*(S*Q2*S)*b)*(2*a'*(S*Q1*S)*a)*(a'*S*a)^2+8*holmquist1(S,Q3)*(2*a'*(S*Q2*S)*b)*(2*a'*(S*Q1*S)*a)*(a'*S*a)+4*holmquist1(S,Q2)*(2*a'*(S*Q3*S)*b)*(2*a'*(S*Q1*S)*a)*(a'*S*a)^2+8*holmquist1(S,Q2)*(2*a'*(S*Q3*S)*b)*(2*a'*(S*Q1*S)*a)*(a'*S*a)-6*holmquist1(S,Q1)*(a'*S*b)*(2*a'*(S*Q2*S)*a)*(2*a'*(S*Q3*S)*a)*(a'*S*a)-6*1*(2*a'*(S*Q3*S)*b)*(2*a'*(S*Q1*S)*a)*(2*a'*(S*Q2*S)*a)*(a'*S*a)-6*1*(2*a'*(S*Q2*S)*b)*(2*a'*(S*Q1*S)*a)*(2*a'*(S*Q3*S)*a)*(a'*S*a)-6*holmquist1(S,Q3)*(a'*S*b)*(2*a'*(S*Q1*S)*a)*(2*a'*(S*Q2*S)*a)*(a'*S*a)-6*holmquist1(S,Q2)*(a'*S*b)*(2*a'*(S*Q1*S)*a)*(2*a'*(S*Q3*S)*a)*(a'*S*a)-6*1*(2*a'*(S*Q1*S)*b)*(2*a'*(S*Q2*S)*a)*(2*a'*(S*Q3*S)*a)*(a'*S*a)+4*1*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*b)*(2*a'*(S*Q2*S)*a)+4*holmquist2(S,Q1,Q3)*(a'*S*b)*(2*a'*(S*Q2*S)*a)+4*1*(2*a'*(S*Q2*S)*b)*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*a)-6*1*(a'*S*b)*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*a)*(2*a'*(S*Q2*S)*a)-6*1*(a'*S*b)*(2*a'*(S*Q1*S)*a)*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*a)-6*1*(a'*S*b)*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*a)*(2*a'*(S*Q3*S)*a)+4*1*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*b)*(2*a'*(S*Q2*S)*a)*(a'*S*a)^2+4*1*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*b)*(2*a'*(S*Q3*S)*a)+4*holmquist1(S,Q1)*(a'*S*b)*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*a)+4*holmquist2(S,Q1,Q2)*(a'*S*b)*(2*a'*(S*Q3*S)*a)+4*1*(2*a'*(S*Q1*S)*b)*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*a)+4*holmquist1(S,Q3)*(a'*S*b)*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*a)+4*1*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*b)*(2*a'*(S*Q1*S)*a)+4*holmquist1(S,Q2)*(a'*S*b)*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*a)+4*holmquist2(S,Q2,Q3)*(a'*S*b)*(2*a'*(S*Q1*S)*a)+4*1*(a'*S*b)*(8*a'*(S*Q1*S*Q2*S*Q3*S+S*Q1*S*Q3*S*Q2*S+S*Q2*S*Q1*S*Q3*S+S*Q2*S*Q3*S*Q1*S+S*Q3*S*Q1*S*Q2*S+S*Q3*S*Q2*S*Q1*S)*a)+4*1*(2*a'*(S*Q3*S)*b)*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*a)-24*holmquist3(S,Q1,Q2,Q3)*(a'*S*b)*(a'*S*a)^2-8*holmquist3(S,Q1,Q2,Q3)*(a'*S*b)*(a'*S*a)^3-24*holmquist3(S,Q1,Q2,Q3)*(a'*S*b)*(a'*S*a)-24*holmquist2(S,Q2,Q3)*(2*a'*(S*Q1*S)*b)*(a'*S*a)^2-8*holmquist2(S,Q2,Q3)*(2*a'*(S*Q1*S)*b)*(a'*S*a)^3-24*holmquist2(S,Q2,Q3)*(2*a'*(S*Q1*S)*b)*(a'*S*a)-24*holmquist1(S,Q2)*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*b)*(a'*S*a)^2-8*holmquist1(S,Q2)*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*b)*(a'*S*a)^3-24*holmquist1(S,Q2)*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*b)*(a'*S*a)-24*holmquist1(S,Q3)*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*b)*(a'*S*a)^2-8*holmquist1(S,Q3)*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*b)*(a'*S*a)^3-24*holmquist1(S,Q3)*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*b)*(a'*S*a)-24*holmquist1(S,Q1)*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*b)*(a'*S*a)^2-8*holmquist1(S,Q1)*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*b)*(a'*S*a)^3-24*holmquist1(S,Q1)*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*b)*(a'*S*a)-8*holmquist1(S,Q3)*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*b)-8*holmquist2(S,Q2,Q3)*(2*a'*(S*Q1*S)*b)-8*holmquist1(S,Q2)*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*b)-8*holmquist2(S,Q1,Q3)*(2*a'*(S*Q2*S)*b)-8*1*(8*a'*(S*Q1*S*Q2*S*Q3*S+S*Q1*S*Q3*S*Q2*S+S*Q2*S*Q1*S*Q3*S+S*Q2*S*Q3*S*Q1*S+S*Q3*S*Q1*S*Q2*S+S*Q3*S*Q2*S*Q1*S)*b)-8*holmquist2(S,Q1,Q2)*(2*a'*(S*Q3*S)*b)-8*holmquist1(S,Q1)*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*b)-8*holmquist3(S,Q1,Q2,Q3)*(a'*S*b)-24*holmquist2(S,Q1,Q2)*(2*a'*(S*Q3*S)*b)*(a'*S*a)^2-8*holmquist2(S,Q1,Q2)*(2*a'*(S*Q3*S)*b)*(a'*S*a)^3-24*holmquist2(S,Q1,Q2)*(2*a'*(S*Q3*S)*b)*(a'*S*a)-24*1*(8*a'*(S*Q1*S*Q2*S*Q3*S+S*Q1*S*Q3*S*Q2*S+S*Q2*S*Q1*S*Q3*S+S*Q2*S*Q3*S*Q1*S+S*Q3*S*Q1*S*Q2*S+S*Q3*S*Q2*S*Q1*S)*b)*(a'*S*a)^2-8*1*(8*a'*(S*Q1*S*Q2*S*Q3*S+S*Q1*S*Q3*S*Q2*S+S*Q2*S*Q1*S*Q3*S+S*Q2*S*Q3*S*Q1*S+S*Q3*S*Q1*S*Q2*S+S*Q3*S*Q2*S*Q1*S)*b)*(a'*S*a)^3-24*1*(8*a'*(S*Q1*S*Q2*S*Q3*S+S*Q1*S*Q3*S*Q2*S+S*Q2*S*Q1*S*Q3*S+S*Q2*S*Q3*S*Q1*S+S*Q3*S*Q1*S*Q2*S+S*Q3*S*Q2*S*Q1*S)*b)*(a'*S*a)-24*holmquist2(S,Q1,Q3)*(2*a'*(S*Q2*S)*b)*(a'*S*a)^2-8*holmquist2(S,Q1,Q3)*(2*a'*(S*Q2*S)*b)*(a'*S*a)^3-24*holmquist2(S,Q1,Q3)*(2*a'*(S*Q2*S)*b)*(a'*S*a)+8*1*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*b)*(2*a'*(S*Q2*S)*a)*(a'*S*a)+4*1*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*b)*(2*a'*(S*Q3*S)*a)*(a'*S*a)^2+8*1*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*b)*(2*a'*(S*Q3*S)*a)*(a'*S*a)+4*holmquist1(S,Q1)*(a'*S*b)*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*a)*(a'*S*a)^2+8*holmquist1(S,Q1)*(a'*S*b)*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*a)*(a'*S*a)+4*holmquist2(S,Q1,Q3)*(a'*S*b)*(2*a'*(S*Q2*S)*a)*(a'*S*a)^2+8*holmquist2(S,Q1,Q3)*(a'*S*b)*(2*a'*(S*Q2*S)*a)*(a'*S*a)+4*holmquist2(S,Q1,Q2)*(a'*S*b)*(2*a'*(S*Q3*S)*a)*(a'*S*a)^2+8*holmquist2(S,Q1,Q2)*(a'*S*b)*(2*a'*(S*Q3*S)*a)*(a'*S*a)+4*1*(2*a'*(S*Q1*S)*b)*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*a)*(a'*S*a)^2+8*1*(2*a'*(S*Q1*S)*b)*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*a)*(a'*S*a)+4*holmquist1(S,Q3)*(a'*S*b)*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*a)*(a'*S*a)^2+8*holmquist1(S,Q3)*(a'*S*b)*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*a)*(a'*S*a)+4*1*(2*a'*(S*Q2*S)*b)*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*a)*(a'*S*a)^2+8*1*(2*a'*(S*Q2*S)*b)*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*a)*(a'*S*a)+4*1*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*b)*(2*a'*(S*Q1*S)*a)*(a'*S*a)^2+8*1*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*b)*(2*a'*(S*Q1*S)*a)*(a'*S*a)+4*holmquist1(S,Q2)*(a'*S*b)*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*a)*(a'*S*a)^2+8*holmquist1(S,Q2)*(a'*S*b)*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*a)*(a'*S*a)+4*holmquist2(S,Q2,Q3)*(a'*S*b)*(2*a'*(S*Q1*S)*a)*(a'*S*a)^2+8*holmquist2(S,Q2,Q3)*(a'*S*b)*(2*a'*(S*Q1*S)*a)*(a'*S*a)+4*1*(a'*S*b)*(8*a'*(S*Q1*S*Q2*S*Q3*S+S*Q1*S*Q3*S*Q2*S+S*Q2*S*Q1*S*Q3*S+S*Q2*S*Q3*S*Q1*S+S*Q3*S*Q1*S*Q2*S+S*Q3*S*Q2*S*Q1*S)*a)*(a'*S*a)^2+8*1*(a'*S*b)*(8*a'*(S*Q1*S*Q2*S*Q3*S+S*Q1*S*Q3*S*Q2*S+S*Q2*S*Q1*S*Q3*S+S*Q2*S*Q3*S*Q1*S+S*Q3*S*Q1*S*Q2*S+S*Q3*S*Q2*S*Q1*S)*a)*(a'*S*a)+4*1*(2*a'*(S*Q3*S)*b)*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*a)*(a'*S*a)^2+8*1*(2*a'*(S*Q3*S)*b)*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*a)*(a'*S*a)-6*1*(a'*S*b)*(4*a'*(S*Q1*S*Q3*S+S*Q3*S*Q1*S)*a)*(2*a'*(S*Q2*S)*a)*(a'*S*a)-6*1*(a'*S*b)*(2*a'*(S*Q1*S)*a)*(4*a'*(S*Q2*S*Q3*S+S*Q3*S*Q2*S)*a)*(a'*S*a)-6*1*(a'*S*b)*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*a)*(2*a'*(S*Q3*S)*a)*(a'*S*a))/(1+(a'*S*a))^(7/2);
15
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group