WAFO. Description of holmquist1
Home > wafo > trgauss > private > holmquist1.m
holmquist1
PURPOSE
Computes moments for higher order reliability methods.
SYNOPSIS
E=holmquist1(S,Q1)
DESCRIPTION
  HOLMQUIST1 Computes moments for higher order reliability methods.
CROSS-REFERENCE INFORMATION
This function calls:
trace
Sum of diagonal elements.
This function is called by:
holmberg2
Computes moments for higher order reliability methods.
holmberg3
Computes moments for higher order reliability methods.
rqlf_asympt
Gives first two terms in an asymptotic expansion of the
SOURCE CODE
01 function E=holmquist1(S,Q1)
02 % HOLMQUIST1 Computes moments for higher order reliability methods.
03
04 S=.5*(S+S');
05 Q1=.5*(Q1+Q1');
06 E=trace(Q1*S);
07
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group