WAFO. Description of holmberg2
Home > wafo > trgauss > private > holmberg2.m
holmberg2
PURPOSE
Computes moments for higher order reliability methods.
SYNOPSIS
E=holmberg2(S,a,b,Q1,Q2)
DESCRIPTION
  HOLMBERG2 Computes moments for higher order reliability methods.
  CALL: E=holmberg2(S,a,b,Q1);
  Computation of the expectation of
  sqrt(pi/2)*(b'*X)*(X'*Q1*X)(X'*Q2*X)*(2*normcdf(a'*X)-1)
  if S is normally distributed with mean zero and covariance matrix
  S.
CROSS-REFERENCE INFORMATION
This function calls:
holmquist1
Computes moments for higher order reliability methods.
holmquist2
Computes moments for higher order reliability methods.
This function is called by:
rqlf_asympt
Gives first two terms in an asymptotic expansion of the
SOURCE CODE
01 function E=holmberg2(S,a,b,Q1,Q2)
02 % HOLMBERG2 Computes moments for higher order reliability methods.
03 %
04 % CALL: E=holmberg2(S,a,b,Q1);
05 %
06 % Computation of the expectation of
07 % sqrt(pi/2)*(b'*X)*(X'*Q1*X)(X'*Q2*X)*(2*normcdf(a'*X)-1)
08 % if S is normally distributed with mean zero and covariance matrix
09 % S.
10 Q1=(Q1+Q1')/2;
11 Q2=(Q2+Q2')/2;
12 E=1/4*(4*holmquist2(S,Q1,Q2)*(a'*S*b)+8*holmquist2(S,Q1,Q2)*(a'*S*b)*(a'*S*a)+...
13     4*holmquist2(S,Q1,Q2)*(a'*S*b)*(a'*S*a)^2+4*holmquist1(S,Q1)*(2*a'*S*Q2*S*b)+...
14     8*holmquist1(S,Q1)*(2*a'*S*Q2*S*b)*(a'*S*a)+4*holmquist1(S,Q1)*(2*a'*S*Q2*S*b)*(a'*S*a)^2-...
15     2*holmquist1(S,Q1)*(a'*S*b)*(2*a'*S*Q2*S*a)-2*holmquist1(S,Q1)*(a'*S*b)*(2*a'*S*Q2*S*a)*(a'*S*a)+...
16     4*holmquist1(S,Q2)*(2*a'*S*Q1*S*b)+8*holmquist1(S,Q2)*(2*a'*S*Q1*S*b)*(a'*S*a)+...
17     4*holmquist1(S,Q2)*(2*a'*S*Q1*S*b)*(a'*S*a)^2+4*1*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*b)+...
18     8*1*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*b)*(a'*S*a)+4*1*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*b)*(a'*S*a)^2-...
19     2*1*(2*a'*S*Q1*S*b)*(2*a'*S*Q2*S*a)-2*1*(2*a'*S*Q1*S*b)*(2*a'*S*Q2*S*a)*(a'*S*a)-...
20     2*holmquist1(S,Q2)*(a'*S*b)*(2*a'*S*Q1*S*a)-2*holmquist1(S,Q2)*(a'*S*b)*(2*a'*S*Q1*S*a)*(a'*S*a)-...
21     2*1*(2*a'*S*Q2*S*b)*(2*a'*S*Q1*S*a)-2*1*(2*a'*S*Q2*S*b)*(2*a'*S*Q1*S*a)*(a'*S*a)+...
22     3*1*(a'*S*b)*(2*a'*S*Q1*S*a)*(2*a'*S*Q2*S*a)-2*1*(a'*S*b)*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*a)-...
23     2*1*(a'*S*b)*(4*a'*(S*Q1*S*Q2*S+S*Q2*S*Q1*S)*a)*(a'*S*a))/(1+(a'*S*a))^(5/2);
24 % Tested in test041104_1.m
25
26
27
28
29
30
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group