WAFO. Description of kchitwo
Home > wafo > trgauss > private > kchitwo.m
kchitwo
PURPOSE
Computes the cumulant generating function formula for noncentral Chi2-process.
SYNOPSIS
[K]=kchitwo(s,t,gam,bet,S12,S22);
DESCRIPTION
  KCHITWO Computes the cumulant generating function formula for noncentral Chi2-process.
  CALL: [K]=kchitwo(s,t,gam,bet,S12,S22);
  Note that s,t must be constants (vectors are not allowed):
CROSS-REFERENCE INFORMATION
This function calls:
det
Determinant.
inv
Matrix inverse.
This function is called by:
chitwo2lc_sp
Saddlepoint approximation of the crossing intensity for the noncentral Chi^2 process
SOURCE CODE
01 function [K]=kchitwo(s,t,gam,bet,S12,S22);
02 % KCHITWO Computes the cumulant generating function formula for noncentral Chi2-process.
03 %
04 % CALL: [K]=kchitwo(s,t,gam,bet,S12,S22);
05 %
06 % Note that s,t must be constants (vectors are not allowed):
07 %
08
09
10 % Reference: "Five lectures on reliability applications of Rice's formula for
11 %             level crossings" Rychlik (2003).
12 %
13 % tested on matlab 6.1
14 % by IR 12.11.03, changed name and added some checks and comments.
15 % rev. IR 24.11.03, changed name and added some checks and comments.
16
17 n=length(gam);
18 V=S22-S12'*S12;
19 Gam=diag(gam);
20 I=eye(n);
21 A=I-2*s*Gam-2*t*(Gam*S12'+S12*Gam)-4*t*t*Gam*V*Gam;
22 T=(s*I+t*S12+2*t*t*Gam*V)*bet';
23 K=-log(det(A))/2+t*t*bet*V*bet'/2+T'*inv(A)*T/2;
24
25
26
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group