WAFO. Description of wafoweb
Home > wafo > docs > wafoweb.m
wafoweb
PURPOSE
World Wide Web site of the WAFO Toolbox.
SYNOPSIS
URLout = wafoweb(ButtonName)
DESCRIPTION
 WAFOWEB  World Wide Web site of the WAFO Toolbox.
   CALL:  URL = wafoweb(BN)
    URL = string with the URL address of WAFO.
    BN  = 'yes' If display URL site
          'no'  If no display of URL site
  WAFOWEB displays and/or returns the WWW
    site for the WAFO Toolbox.  If no input argument
    is givendisplayed, a dialog asks whether to go there.
  Examples
   url = wafoweb('n'); web(url)
   wafoweb
   wafoweb('yes')
  See also  web
CROSS-REFERENCE INFORMATION
This function calls:
help
Display help text in Command Window.
questdlg
Question dialog box.
strncmpi
Compare first N characters of strings ignoring case.
web
Open Web browser on site or files.
This function is called by:
SOURCE CODE
001 function URLout = wafoweb(ButtonName)
002 %WAFOWEB  World Wide Web site of the WAFO Toolbox.
003 %
004 %  CALL:  URL = wafoweb(BN)
005 %
006 %   URL = string with the URL address of WAFO.
007 %   BN  = 'yes' If display URL site
008 %         'no'  If no display of URL site
009 %
010 % WAFOWEB displays and/or returns the WWW
011 %   site for the WAFO Toolbox.  If no input argument
012 %   is givendisplayed, a dialog asks whether to go there.
013 %
014 % Examples
015 %  url = wafoweb('n'); web(url)
016 %  wafoweb
017 %  wafoweb('yes')
018 %
019 % See also  web
020
021 % Tested on: Matlab 5.2
022 % History:
023 % by pab 19.06.2001
024
025 URL = 'http://www.maths.lth.se/matstat/wafo/';
026
027 if nargin<1|isempty(ButtonName),
028   %if nargout>0, ButtonName = 'No';  else,    ButtonName ='Yes';  end
029   ButtonName =  questdlg('Go To WAFO Toolbox Home Page?', 'WWW', 'Yes', 'No', 'No');
030 end
031
032
033
034 if nargout > 0,
035   URLout = URL;
036 else
037   disp(['WAFO Toolbox Home Page:'])
038   disp(URL)
039 end
040
041 if strncmpi(ButtonName, 'y',1)
042
043   Status = web(URL);
044
045   switch Status
046     case 1,
047       disp(' Web Browser not found.')
048       disp(' See "help web".')
049       help(web)
050     case 2,
051       disp(' Web Browser found, but could not be launched.')
052       disp(' See "help web".')
053       help(web)
054     otherwise
055   end
056 end
057 return
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group