WAFO. Description of wafohelp
Home > wafo > docs > wafohelp.m
wafohelp
PURPOSE
Launch HTML help for the WAFO Toolbox.
SYNOPSIS
URLout = wafohelp(ButtonName)
DESCRIPTION
 WAFOHELP  Launch HTML help for the WAFO Toolbox.
   CALL:  URL = wafohelp(BN)
    URL = string with the URL address of WAFO.
    BN  = 'yes' If display URL site
          'no'  If no display of URL site
  WAFOHELP displays and/or returns the HTML help
    site for the WAFO Toolbox.
  Examples
   url = wafohelp('n'); web(url)
   wafohelp
   wafohelp('yes')
  See also  web
CROSS-REFERENCE INFORMATION
This function calls:
waforoot
Root directory of WAFO installation.
fullfile
Build full filename from parts.
help
Display help text in Command Window.
strncmpi
Compare first N characters of strings ignoring case.
web
Open Web browser on site or files.
This function is called by:
SOURCE CODE
001 function URLout = wafohelp(ButtonName)
002 %WAFOHELP  Launch HTML help for the WAFO Toolbox.
003 %
004 %  CALL:  URL = wafohelp(BN)
005 %
006 %   URL = string with the URL address of WAFO.
007 %   BN  = 'yes' If display URL site
008 %         'no'  If no display of URL site
009 %
010 % WAFOHELP displays and/or returns the HTML help
011 %   site for the WAFO Toolbox.
012 %
013 % Examples
014 %  url = wafohelp('n'); web(url)
015 %  wafohelp
016 %  wafohelp('yes')
017 %
018 % See also  web
019
020 % Tested on: Matlab 5.2
021 % History:
022 % by pab 19.11.2004
023
024 URL = fullfile(waforoot,'docs','wafodoc', 'index.html');
025
026 if nargin<1|isempty(ButtonName),
027   if nargout>0,
028     ButtonName = 'No';
029   else,
030     ButtonName ='Yes';
031   end
032   %ButtonName =  questdlg('Go To WAFO Toolbox Home Page?', 'WWW', 'Yes', 'No', 'No');
033 end
034
035
036
037 if nargout > 0,
038   URLout = URL;
039 else
040   disp(['WAFO Toolbox Help Page:'])
041   disp(URL)
042 end
043
044 if strncmpi(ButtonName, 'y',1)
045
046   Status = web(URL,'-browser');
047
048   switch Status
049     case 1,
050       disp(' Web Browser not found.')
051       disp(' See "help web".')
052       help(web)
053     case 2,
054       disp(' Web Browser found, but could not be launched.')
055       disp(' See "help web".')
056       help(web)
057     otherwise
058   end
059 end
060 return
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group