WAFO. Description of recdemo
Home > wafo > papers > rec > recdemo.m
recdemo
PURPOSE
Show Rec figures with point and click interface
SYNOPSIS
recdemo
DESCRIPTION
  RECDEMO  Show Rec figures with point and click interface
  CALL:    recdemo
CROSS-REFERENCE INFORMATION
This function calls:
choices
Create a list of choices with uicontrols and callbacks.
recintro
Info about RECDEMO: A statistical procedure for reconstruction of 1D signals.
clc
Clear command window.
str2mat
Form blank padded character matrix from strings.
strvcat
Vertically concatenate strings.
This function is called by:
SOURCE CODE
01 function recdemo
02 % RECDEMO  Show Rec figures with point and click interface
03 %
04 % CALL:    recdemo
05 %
06
07 % By pab 28.01.2000
08
09 header = 'Reconstruction Demo';
10 labels =strvcat('Change Settings' , 'Run All Scripts' , ...
11           'Run One Script' , 'Clean Up');
12 callbacks = str2mat('recfig(-1)', 'recfig(-2)', ...
13              'recfig(-3)', 'recleanup');
14 global RECFIGNUM
15 RECFIGNUM = 0;
16 clc;
17 %figure(gcf+1)
18 recintro
19 choices('Rec',header,labels,callbacks);
20
21
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group