WAFO. Description of recfig12
Home > wafo > papers > rec > recfig12.m
recfig12
PURPOSE
Probability of exceeding V: Model (dash); data (dots)
SYNOPSIS
recfig12
DESCRIPTION
  RECFIG12 Probability of exceeding V: Model (dash); data (dots)
CROSS-REFERENCE INFORMATION
This function calls:
dist2dcdf
Joint 2D CDF computed as int F(X1
empdistr
Computes and plots the empirical CDF
wafostamp
Prints a caption "made by WAFO" in current figure.
axis
Control axis scaling and appearance.
hold
Hold current graph.
linspace
Linearly spaced vector.
semilogy
Semi-log scale plot.
square
Square wave generation.
title
Graph title.
xlabel
X-axis label.
ylabel
Y-axis label.
This function is called by:
SOURCE CODE
01 function recfig12
02 % RECFIG12 Probability of exceeding V: Model (dash); data (dots)
03 %
04
05
06 % History
07 % Revised pab 12.06.2001
08 %  changed from empdistr(V/Vrms,0,[x F],2); to  empdistr(V/Vrms,[x F],2);
09 % By pab
10 global RECFIGNUM
11 if isempty(RECFIGNUM)
12   disp('You must start recdemo in order to run this script')
13   return
14 end
15
16 global V Vrms sphat
17 x=linspace(0,3.5)';
18 F=dist2dcdf(x,20,sphat,0);
19 empdistr(V/Vrms,[x F],2);
20 hold on,
21 semilogy(x(F<1),1-F(F(:)<1),'r--')
22 hold off
23 xlabel('v')
24 ylabel('1-F(v)')
25 title('')
26 axis([0 3.5 1e-4 1])
27 axis square
28 wafostamp('Figure 12','(NR)')
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group