WAFO. Description of recfig1
Home > wafo > papers > rec > recfig1.m
recfig1
PURPOSE
Location of Gullfaks C and Statfjord A platforms in The North Sea
SYNOPSIS
recfig1
DESCRIPTION
  RECFIG1  Location of Gullfaks C and Statfjord A platforms in The North Sea
CROSS-REFERENCE INFORMATION
This function calls:
wafostamp
Prints a caption "made by WAFO" in current figure.
axis
Control axis scaling and appearance.
gca
Get handle to current axis.
grid
Grid lines.
hold
Hold current graph.
line
Create line.
plot
Linear plot.
set
Set object properties.
text
Text annotation.
This function is called by:
SOURCE CODE
001 function recfig1
002 % RECFIG1  Location of Gullfaks C and Statfjord A platforms in The North Sea
003 %
004
005 global  RECFIGNUM
006
007 if isempty(RECFIGNUM)
008   disp('You must start recdemo in order to run this script')
009   return
010 end
011
012 global map
013
014 plot(map(:,1),map(:,2))
015 axis([-2 12 58 64])
016 h = gca;
017 set(h,'xticklabel', [2 0:2:12]);
018
019 grid on
020
021 hold on
022 text(1,62     ,'Statfjord A')
023 line([1.8, 1.8], [62  ,61.2 ])
024 plot(1.8,61.2,'x')
025
026 text(1,59.5,'Gullfaks C')
027 line([1.8, 2.3 ], [59.50 ,61.20 ])
028 plot(2.30,61.20,'x')
029
030 text(10.40,60.10,'Oslo')
031 plot(10.80,59.85,'h')
032 text(10.00,63.05,'Trondheim')
033 plot(10.80,63.40,'h')
034 text(4.00,58.80,'Stavanger')
035 plot(5.52,58.90,'h')
036 text(3.50,60.30,'Bergen')
037 plot(5.20,60.30,'h')
038 hold off
039 wafostamp('Figure 1','(ER)')
040
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group