WAFO. Description of recfig10
Home > wafo > papers > rec > recfig10.m
recfig10
PURPOSE
Joint distribution of V and H:
SYNOPSIS
recfig10
DESCRIPTION
  RECFIG10 Joint distribution of  V and H:
          Fitted distribution (solid); Kernel density (dash); data (dots)
CROSS-REFERENCE INFORMATION
This function calls:
pdfplot
Plot contents of pdf structures
wafostamp
Prints a caption "made by WAFO" in current figure.
axis
Control axis scaling and appearance.
hold
Hold current graph.
plot
Linear plot.
square
Square wave generation.
title
Graph title.
This function is called by:
SOURCE CODE
01 function recfig10
02 % RECFIG10 Joint distribution of  V and H:
03 %         Fitted distribution (solid); Kernel density (dash); data (dots)
04 %
05
06 global RECFIGNUM
07 if isempty(RECFIGNUM)
08   disp('You must start recdemo in order to run this script')
09   return
10 end
11 global V H Hrms Vrms ft2 fkde
12
13 plot(V/Vrms,H/Hrms,'k.')
14 axis([0 3.5 0 3.5]), axis square
15 hold on
16 pdfplot(ft2,1,'k')
17 %hold on
18 pdfplot(fkde,1,'k--')
19 title('Joint distribution of v and h')
20 hold off
21 wafostamp('Figure 10','(NR)')
22
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group