WAFO. Description of recfig6
Home > wafo > papers > rec > recfig6.m
recfig6
PURPOSE
Variability of simulated e(g(u)-u) (circles)
SYNOPSIS
recfig6
DESCRIPTION
  RECFIG6 Variability of simulated e(g(u)-u) (circles)
          for Gaussian processes with the same spectral densities and
          lengths as the reconstructed data set compared with the
          observed e(g(u)-u) for the reconstructed data set (dash)
CROSS-REFERENCE INFORMATION
This function calls:
mctrtest
Test if a stochastic process is Gaussian.
troptset
Create or alter TRANSFORM OPTIONS structure.
wafostamp
Prints a caption "made by WAFO" in current figure.
This function is called by:
SOURCE CODE
01 function recfig6
02 % RECFIG6 Variability of simulated e(g(u)-u) (circles)
03 %         for Gaussian processes with the same spectral densities and
04 %         lengths as the reconstructed data set compared with the
05 %         observed e(g(u)-u) for the reconstructed data set (dash)
06 %
07
08 % revised pab 2 Sept 2005
09 %  -updated order of arguments to mctrtest once again.
10 % revised pab 18.04.2001
11 % updated call to mctrtest.
12
13 global RECFIGNUM
14 if isempty(RECFIGNUM)
15   disp('You must start recdemo in order to run this script')
16   return
17 end
18
19 global Sr test0 csm1 csm2 param
20
21 %Ns=100; %This takes a while and is used in the article
22 Ns=50;
23 opt = troptset('csm',csm1,'gsm',csm2,'param',param);
24 test1 = mctrtest(Sr,[36000,Ns],test0,[],opt);
25 wafostamp('Figure 6','(NR)')
26
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group