WAFO. Description of recfig11
Home > wafo > papers > rec > recfig11.m
recfig11
PURPOSE
Probability of exceeding H: Model (dash); data (dots)
SYNOPSIS
recfig11
DESCRIPTION
  RECFIG11 Probability of exceeding H: Model (dash); data (dots)
CROSS-REFERENCE INFORMATION
This function calls:
dist2dcdf
Joint 2D CDF computed as int F(X1
empdistr
Computes and plots the empirical CDF
wafostamp
Prints a caption "made by WAFO" in current figure.
axis
Control axis scaling and appearance.
hold
Hold current graph.
linspace
Linearly spaced vector.
semilogy
Semi-log scale plot.
square
Square wave generation.
title
Graph title.
xlabel
X-axis label.
ylabel
Y-axis label.
This function is called by:
SOURCE CODE
01 function recfig11
02 % RECFIG11 Probability of exceeding H: Model (dash); data (dots)
03 %
04
05 % Tested on: Matlab 5.x
06 % History:
07 % Revised pab 12.06.2001
08 %  changed from empdistr(H/Hrms,0,[x F],2); to  empdistr(H/Hrms,[x F],2);
09 global RECFIGNUM
10 if isempty(RECFIGNUM)
11   disp('You must start recdemo in order to run this script')
12   return
13 end
14 global H Hrms sphat
15 x=linspace(0,3.5)';
16 F=dist2dcdf(20,x,sphat,0);
17 empdistr(H/Hrms,[x F],2);
18 xlabel('h')
19 ylabel('1-F(h)')
20 title('')
21 hold on,
22 semilogy(x(F<1),1-F(F(:)<1),'r--')
23 hold off
24 axis([0 3.5 1e-4 1])
25 axis square
26 wafostamp('Figure 11','(NR)')
27
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group