WAFO. Description of recfig4
Home > wafo > papers > rec > recfig4.m
recfig4
PURPOSE
Estimated spectral density (solid) and 95% confidence intervals (dots)
SYNOPSIS
recfig4
DESCRIPTION
  RECFIG4 Estimated spectral density (solid) and 95% confidence intervals (dots)
CROSS-REFERENCE INFORMATION
This function calls:
ttspec
Toggle Transform between angular frequency and frequency spectrum
wafostamp
Prints a caption "made by WAFO" in current figure.
wspecplot
Plot a spectral density
This function is called by:
SOURCE CODE
01 function recfig4
02 % RECFIG4 Estimated spectral density (solid) and 95% confidence intervals (dots)
03 %
04 %
05
06 global RECFIGNUM
07 if isempty(RECFIGNUM)
08   disp('You must start recdemo in order to run this script')
09   return
10 end
11
12 global Sr
13 Sf=ttspec(Sr,'f');
14 wspecplot(Sf)
15 wafostamp('Figure 4','(NR)')
16
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group