WAFO. Description of recfig8
Home > wafo > papers > rec > recfig8.m
recfig8
PURPOSE
Estimated Weibull shape parameter versus h=H/Hrms (circles)
SYNOPSIS
recfig8
DESCRIPTION
  RECFIG8 Estimated Weibull shape parameter versus h=H/Hrms (circles)
          and 95% pointwise confidence intervals (dash) compared
          with the final smoothed estimate (solid).
CROSS-REFERENCE INFORMATION
This function calls:
dist2dparamplot
Plot parameters of the conditional distribution
wafostamp
Prints a caption "made by WAFO" in current figure.
xlabel
X-axis label.
ylabel
Y-axis label.
This function is called by:
SOURCE CODE
01 function recfig8
02 % RECFIG8 Estimated Weibull shape parameter versus h=H/Hrms (circles)
03 %         and 95% pointwise confidence intervals (dash) compared
04 %         with the final smoothed estimate (solid).
05 %
06
07 global RECFIGNUM
08 if isempty(RECFIGNUM)
09   disp('You must start recdemo in order to run this script')
10   return
11 end
12 global phat sphat
13
14 dist2dparamplot(phat,sphat,2)
15 ylabel('B(h)')
16 xlabel('h')
17 wafostamp('Figure 8','(NR)')
18
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group