WAFO. Description of recfig5
Home > wafo > papers > rec > recfig5.m
recfig5
PURPOSE
Transfer function, g, versus the crossing level u
SYNOPSIS
recfig5
DESCRIPTION
  RECFIG5 Transfer function, g, versus the crossing level u
      of the reconstructed time series estimated by smooting (solid)
      compared with empirical estimate (irregular) and the theoretical
      one for a Gaussian process (dash).
CROSS-REFERENCE INFORMATION
This function calls:
trplot
Plots transformation, g, eg. estimated with dat2tr.
wafostamp
Prints a caption "made by WAFO" in current figure.
mean
Average or mean value.
This function is called by:
SOURCE CODE
01 function recfig5
02 % RECFIG5 Transfer function, g, versus the crossing level u
03 %     of the reconstructed time series estimated by smooting (solid)
04 %     compared with empirical estimate (irregular) and the theoretical
05 %     one for a Gaussian process (dash).
06 %
07
08 global RECFIGNUM
09 if isempty(RECFIGNUM)
10   disp('You must start recdemo in order to run this script')
11   return
12 end
13 global xr m0 g g2
14 trplot(g, g2,mean(xr(:,2)),sqrt(m0))
15 wafostamp('Figure 5','(NR)')
16
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group