WAFO. Description of recfig3
Home > wafo > papers > rec > recfig3.m
recfig3
PURPOSE
Example of the reconstructed (solid) and original data set (pluses)
SYNOPSIS
recfig3
DESCRIPTION
  RECFIG3 Example of the reconstructed (solid) and original data set (pluses)
          Use the mouse to zoom in on a specific region
CROSS-REFERENCE INFORMATION
This function calls:
wafostamp
Prints a caption "made by WAFO" in current figure.
waveplot
Plots the surface elevation of timeseries.
zoom
Zoom in and out on a 2-D plot.
This function is called by:
SOURCE CODE
01 function recfig3
02 % RECFIG3 Example of the reconstructed (solid) and original data set (pluses)
03 %         Use the mouse to zoom in on a specific region
04 %
05
06 global RECFIGNUM
07 if isempty(RECFIGNUM)
08   disp('You must start recdemo in order to run this script')
09   return
10 end
11
12 global xn xr m0 inds
13 %choose a random place to see how it looks
14 Ns=ceil(rand*length(xr));
15 %if (rand<27/39),
16 % Ns=ceil(rand*26000);
17 %else
18 % Ns=ceil(30000+rand*8700);
19 %end
20
21 waveplot(xr,'k-',xn(inds,:), 1,1,sqrt(m0),4)
22 zoom xon
23 %axis([xr(Ns,1)/60 xr(Ns+100,1)/60 -7 7])
24 %waveplot(xr(20201:20300,:),xn(inds,:), 1,1,sqrt(m0),4)
25 wafostamp('Figure 3','(NR)')
26
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group