WAFO. Description of recintro
Home > wafo > papers > rec > recintro.m
recintro
PURPOSE
Info about RECDEMO: A statistical procedure for reconstruction of 1D signals.
SYNOPSIS
recintro
DESCRIPTION
  RECINTRO  Info about RECDEMO: A statistical procedure for reconstruction of 1D signals.
  The files in this directory can reproduce the figures in the
  article of
  Brodtkorb, P.A., Myrhaug, D. and Rue, H (1999)
  'Joint distribution of wave height and wave crest velocity
   from reconstructed data.'
   in Proceedings of 9th ISOPE Conference, Vol III, pp 66-73
  The paper shows a method for reconstruction of missing and or spurious
  data points of a recorded time series by using a transformed Gaussian
  process. The application of the result is illustrated by fitting a
  joint distribution to the maximum of the crest front velocity and crest back velocity
  (V = max(Vcf,Vcb)) and the corresponding wave height (H = Hd or Hu)
  obtained from the reconstructed data set. The joint distribution seem to be physically
  sound and much better described using the reconstructed than the
  original time series. (Note that the extracted data are normalized with
  the rms values, i.e., v=V/Vrms and h=H/Hrms)
  The joint probability distribution given as the product of the
  Rayleigh distribution of wave heights and the Weibull distribution
  for the conditional crest velocity (v) given wave height (h) seem to be
  a reasonable model.
   DATA: GFAKS89.DAT
  ~~~~~~~~~~~~~~~~~~~
  The wave data considered was measured 24th December 1989 at the Gullfaks C platform
  in the North Sea from 17.00 to 21.20. The period from 20.00 to 20.20
  is missing and contains NaNs.  The  water depth of  218 m is
  regarded as deep water for the most  important wave components.
  There are two EMI laser sensors named 219 and 220. This data set is
  obtained from sensor 219, which is  located in the Northwest
  corner  approximately two platform leg diameters away from
  the closest leg.
    Thus the wave elevation is not expected  to be significantly
  affected by  diffraction effects for incoming waves in the western sector.
  The wind direction for this period is from the south.
  Some  difficulties in calibration of the instruments have been reported
  resulting in several consecutive measured values being equal or nearly equal
  in the observed data set.
  Hm0 = 6.8m, Tm02 = 8s, Tp = 10.5 Tp2=19
  Wind data from Statfjord A, 1989 are also given to justify the
  assumption that the data may be regarded as stationary.
CROSS-REFERENCE INFORMATION
This function calls:
recintro
Info about RECDEMO: A statistical procedure for reconstruction of 1D signals.
help
Display help text in Command Window.
This function is called by:
recdemo
Show Rec figures with point and click interface
recintro
Info about RECDEMO: A statistical procedure for reconstruction of 1D signals.
SOURCE CODE
001 function recintrorecintro
002 % RECINTRO  Info about RECDEMO: A statistical procedure for reconstruction of 1D signals.
003 %
004 % The files in this directory can reproduce the figures in the
005 % article of
006 %
007 % Brodtkorb, P.A., Myrhaug, D. and Rue, H (1999)
008 % 'Joint distribution of wave height and wave crest velocity
009 %  from reconstructed data.'
010 %  in Proceedings of 9th ISOPE Conference, Vol III, pp 66-73
011 %
012 %
013 % The paper shows a method for reconstruction of missing and or spurious
014 % data points of a recorded time series by using a transformed Gaussian
015 % process. The application of the result is illustrated by fitting a
016 % joint distribution to the maximum of the crest front velocity and crest back velocity
017 % (V = max(Vcf,Vcb)) and the corresponding wave height (H = Hd or Hu)
018 % obtained from the reconstructed data set. The joint distribution seem to be physically
019 % sound and much better described using the reconstructed than the
020 % original time series. (Note that the extracted data are normalized with
021 % the rms values, i.e., v=V/Vrms and h=H/Hrms)
022 % The joint probability distribution given as the product of the
023 % Rayleigh distribution of wave heights and the Weibull distribution
024 % for the conditional crest velocity (v) given wave height (h) seem to be
025 % a reasonable model.
026 %
027 %  DATA: GFAKS89.DAT
028 % ~~~~~~~~~~~~~~~~~~~
029 % The wave data considered was measured 24th December 1989 at the Gullfaks C platform
030 % in the North Sea from 17.00 to 21.20. The period from 20.00 to 20.20
031 % is missing and contains NaNs.  The  water depth of  218 m is
032 % regarded as deep water for the most  important wave components.
033 % There are two EMI laser sensors named 219 and 220. This data set is
034 % obtained from sensor 219, which is  located in the Northwest
035 % corner  approximately two platform leg diameters away from
036 % the closest leg.
037 %   Thus the wave elevation is not expected  to be significantly
038 % affected by  diffraction effects for incoming waves in the western sector.
039 % The wind direction for this period is from the south.
040 % Some  difficulties in calibration of the instruments have been reported
041 % resulting in several consecutive measured values being equal or nearly equal
042 % in the observed data set.
043 %
044 % Hm0 = 6.8m, Tm02 = 8s, Tp = 10.5 Tp2=19
045 %
046 % Wind data from Statfjord A, 1989 are also given to justify the
047 % assumption that the data may be regarded as stationary.
048
049
050
051
052 % By pab 28.01.2000
053
054 %more on
055 help recintro
056 %more off
057
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group