WAFO. Description of mctp2rfm
Home > wafo > markov > mctp2rfm.m
mctp2rfm
PURPOSE
Calculates the rainflow matrix for a MCTP.
SYNOPSIS
[F_rfc,mu_rfc] = mctp2rfm(F,c_m)
DESCRIPTION
  MCTP2RFM  Calculates the rainflow matrix for a MCTP.
  CALL:  [Frfc,mu_rfc] = mtp2rfc(F);
         [Frfc,mu_rfc] = mtp2rfc(F,c_m);
  Frfc   = Rainflow Matrix (Rainflow Intensity)       [n,n]
  mu_rfc = Rainflow Counting Intensity                [n,n]
  F      = Cell array of min-Max and Max-min matrices {1,2}
  F{1,1} = min-Max matrix                             [n,n]
  F{1,2} = Max-min matrix                             [n,n]
  c_m    = Intensity of local minima
  If the matrix F{1,2} (F{1,2}=[]) is not given, then the process will
  be assumed to be time-reversible.
  Calculates the rainflow matrix for a Markov chain of
    turning points.
  Example:
    param = [-1 1 32]; u = levels(param);
    F = mktestmat(param,[-0.2 0.2],0.15,2);
    Frfc = mctp2rfm({F []});
    cmatplot(u,u,Frfc)
  See also  rfm2mctp, smctp2rfm, mctp2arfm, cmatplot, mc2rfm
CROSS-REFERENCE INFORMATION
This function calls:
smctp2rfm
Calculates the rainflow matrix for a SMCTP.
error
Display message and abort function.
This function is called by:
Chapter4
% CHAPTER4 contains the commands used in Chapter 4 of the tutorial
itmkurs_lab2
Script to computer exercises 2
test_cycles
Quick test of the routines in module 'cycles'
test_markov
Quick test of the routines in module 'markov'
wafofig9
Intensity of rainflow cycles computed from St
SOURCE CODE
001 function [F_rfc,mu_rfc] = mctp2rfm(F,c_m)
002 % MCTP2RFM  Calculates the rainflow matrix for a MCTP.
003 %
004 % CALL:  [Frfc,mu_rfc] = mtp2rfc(F);
005 %        [Frfc,mu_rfc] = mtp2rfc(F,c_m);
006 %
007 % Frfc   = Rainflow Matrix (Rainflow Intensity)       [n,n]
008 % mu_rfc = Rainflow Counting Intensity                [n,n]
009 %
010 % F      = Cell array of min-Max and Max-min matrices {1,2}
011 % F{1,1} = min-Max matrix                             [n,n]
012 % F{1,2} = Max-min matrix                             [n,n]
013 % c_m    = Intensity of local minima
014 %
015 % If the matrix F{1,2} (F{1,2}=[]) is not given, then the process will
016 % be assumed to be time-reversible.
017 %
018 % Calculates the rainflow matrix for a Markov chain of
019 %   turning points.
020 %
021 % Example:
022 %   param = [-1 1 32]; u = levels(param);
023 %   F = mktestmat(param,[-0.2 0.2],0.15,2);
024 %   Frfc = mctp2rfm({F []});
025 %   cmatplot(u,u,Frfc)
026 %
027 % See also  rfm2mctp, smctp2rfm, mctp2arfm, cmatplot, mc2rfm
028
029 % References
030 %
031 %  P. Johannesson (1999):
032 %  Rainflow Analysis of Switching Markov Loads.
033 %  PhD thesis, Mathematical Statistics, Centre for Mathematical Sciences,
034 %  Lund Institute of Technology.
035 %
036 %  P. Johannesson (1998):
037 %  Rainflow Cycles for Switching Processes with Markov Structure.
038 %  Probability in the Engineering and Informational Sciences,
039 %  Vol. 12, No. 2, pp. 143-175.
040
041 % Tested  on Matlab  5.3
042 %
043 % History:
044 % Revised by PJ  23-Nov-1999
045 %   updated for WAFO
046 % Created by PJ (Pär Johannesson) 1997
047 %   Copyright (c) 1997 by Pär Johannesson
048 %   Toolbox: Rainflow Cycles for Switching Processes V.1.0, 2-Oct-1997
049
050 % Check input arguments
051
052 ni = nargin;
053 no = nargout;
054 error(nargchk(1,2,ni));
055
056 if ni < 2
057   c_m=[];
058 end
059
060 [F_rfc,mu_rfc] = smctp2rfm(1,F,c_m);
061
062
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group