WAFO. Description of b04pdf2
Home > wafo > wavemodels > b04pdf2.m
b04pdf2
PURPOSE
Brodtkorb (2004) joint (Scf,Hd) PDF of laboratory data.
SYNOPSIS
p = b04pdf2(Hd,Scf,Hs,Tz,normalizedInput)
DESCRIPTION
 B04PDF2 Brodtkorb  (2004) joint (Scf,Hd) PDF of laboratory data.
     CALL:  f = b04pdf2(Hd,Scf,Hm0,Tm02)
        f  = density
       Hd  = zero down crossing wave height
       Scf = crest front steepness
       Hm0 = significant wave height.
      Tm02 = average zero down crossing period.
     B04PDF2 returns the joint PDF of (Scf, Hd) given Hm0 and Tm02,
     i.e., crest front steepness (2*pi*Ac/(g*Td*Tcf)) and wave height,
     given the seastate. The root mean square values of Hd and Scf
     (Hrms,Erms) are related to the significant waveheight and the
     average zero down crossing period by:
                 Hrms = Hm0/sqrt(2);
                 Erms = 5/4*Hm0/(Tm02^2);
     This distribution  is fitted to laboratory storm waves.
     The size of f is the common size of  the input arguments
  Example:
   Hs = 7;Tz=10;
   h = linspace(0,3*Hs)';
   s = linspace(0,3*5/4*Hs/Tz^2)';
   f = b04pdf2(h,s,Hs,Tz);
   pdfplot(f)
  See also mk87pdf2
CROSS-REFERENCE INFORMATION
This function calls:
b04pdf
Brodtkorb (2004) joint (Scf,Hd) PDF of laboratory data.
createpdf
PDF class constructor
qlevels
Calculates quantile levels which encloses P% of PDF
error
Display message and abort function.
meshgrid
X and Y arrays for 3-D plots.
This function is called by:
SOURCE CODE
001 function p = b04pdf2(Hd,Scf,Hs,Tz,normalizedInput)
002 %B04PDF2 Brodtkorb  (2004) joint (Scf,Hd) PDF of laboratory data.
003 %
004 %    CALL:  f = b04pdf2(Hd,Scf,Hm0,Tm02)
005 %
006 %       f  = density
007 %      Hd  = zero down crossing wave height
008 %      Scf = crest front steepness
009 %      Hm0 = significant wave height.
010 %     Tm02 = average zero down crossing period.
011 %
012 %    B04PDF2 returns the joint PDF of (Scf, Hd) given Hm0 and Tm02,
013 %    i.e., crest front steepness (2*pi*Ac/(g*Td*Tcf)) and wave height,
014 %    given the seastate. The root mean square values of Hd and Scf
015 %    (Hrms,Erms) are related to the significant waveheight and the
016 %    average zero down crossing period by:
017 %                Hrms = Hm0/sqrt(2);
018 %                Erms = 5/4*Hm0/(Tm02^2);
019 %    This distribution  is fitted to laboratory storm waves.
020 %    The size of f is the common size of  the input arguments
021 %
022 % Example:
023 %  Hs = 7;Tz=10;
024 %  h = linspace(0,3*Hs)';
025 %  s = linspace(0,3*5/4*Hs/Tz^2)';
026 %  f = b04pdf2(h,s,Hs,Tz);
027 %  pdfplot(f)
028 %
029 % See also mk87pdf2
030
031 % Reference
032 % P. A. Brodtkorb (2004),
033 % The Probability of Occurrence of Dangerous Wave Situations at Sea.
034 % Dr.Ing thesis, Norwegian University of Science and Technolgy, NTNU,
035 % Trondheim, Norway.
036
037
038 % By pab 15 July 2004
039
040 error(nargchk(3,5,nargin))
041 if nargin < 5|isempty(normalizedInput), normalizedInput = 0; end
042 if nargin < 4|isempty(Tz),  Tz = 8; end
043 if nargin < 3|isempty(Hs),  Hs = 6; end
044
045 p     = createpdf(2);
046
047 [X,Y] = meshgrid(Scf,Hd);
048 p.f   = b04pdf(Y,X,Hs,Tz,0,normalizedInput);
049 p.x{1} = Scf(:);
050 p.x{2} = Hd(:);
051 %p.labx{1}='Crest front steepness';
052 %p.labx{2}='Wave height [m]';
053 if (normalizedInput)
054   p.labx={'Scf', 'Hd'};
055   p.norm = 1;
056 else
057   p.norm=0;
058   p.labx={'Scf', 'Hd [m]'};
059 end
060 p.title='Brodtkorb (2004) density of crest front steepness and wave height.';
061
062 [p.cl p.pl]=qlevels(p.f,[10:20:90 95 99 99.9]);
063
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group