WAFO. Description of bmr00pdf2
Home > wafo > wavemodels > bmr00pdf2.m
bmr00pdf2
PURPOSE
Brodtkorb et.al (2000) joint (Scf,Hd) PDF from North Sea.
SYNOPSIS
p = bmr00pdf2(Hd,Scf,Hs,Tz,normalizedInput)
DESCRIPTION
 BMR00PDF2 Brodtkorb et.al (2000) joint (Scf,Hd) PDF from North Sea.
     CALL:  f = bmr00pdf(Hd,Scf,Hm0,Tm02)
        f  = density
       Hd  = zero down crossing wave height
       Scf = crest front steepness
       Hm0 = significant wave height.
      Tm02 = average zero down crossing period.
     BMR00PDF returns the joint PDF of (Scf, Hd) given Hm0 and Tm02,
     i.e., crest front steepness (2*pi*Ac/(g*Td*Tcf)) and wave height,
     given the seastate. The root mean square values of Hd and Scf
     (Hrms,Erms) are related to the significant waveheight and the
     average zero down crossing period by:
                 Hrms = Hm0/sqrt(2);
                 Erms = 5/4*Hm0/(Tm02^2);
     This is a revised distribution of MK87 and is fitted to storm waves
     from 1995 obtained from the Draupner field in the North Sea.
     The size of f is the common size of  the input arguments
  Example:
   Hs = 7;Tz=10;
   h = linspace(0,3*Hs)';
   s = linspace(0,3*5/4*Hs/Tz^2)';
   f = bmr00pdf2(h,s,Hs,Tz);
   pdfplot(f)
  See also mk87pdf2
CROSS-REFERENCE INFORMATION
This function calls:
bmr00pdf
Brodtkorb et.al (2000) joint (Scf,Hd) PDF from North Sea.
createpdf
PDF class constructor
qlevels
Calculates quantile levels which encloses P% of PDF
error
Display message and abort function.
meshgrid
X and Y arrays for 3-D plots.
This function is called by:
SOURCE CODE
001 function p = bmr00pdf2(Hd,Scf,Hs,Tz,normalizedInput)
002 %BMR00PDF2 Brodtkorb et.al (2000) joint (Scf,Hd) PDF from North Sea.
003 %
004 %    CALL:  f = bmr00pdf(Hd,Scf,Hm0,Tm02)
005 %
006 %       f  = density
007 %      Hd  = zero down crossing wave height
008 %      Scf = crest front steepness
009 %      Hm0 = significant wave height.
010 %     Tm02 = average zero down crossing period.
011 %
012 %    BMR00PDF returns the joint PDF of (Scf, Hd) given Hm0 and Tm02,
013 %    i.e., crest front steepness (2*pi*Ac/(g*Td*Tcf)) and wave height,
014 %    given the seastate. The root mean square values of Hd and Scf
015 %    (Hrms,Erms) are related to the significant waveheight and the
016 %    average zero down crossing period by:
017 %                Hrms = Hm0/sqrt(2);
018 %                Erms = 5/4*Hm0/(Tm02^2);
019 %    This is a revised distribution of MK87 and is fitted to storm waves
020 %    from 1995 obtained from the Draupner field in the North Sea.
021 %    The size of f is the common size of  the input arguments
022 %
023 % Example:
024 %  Hs = 7;Tz=10;
025 %  h = linspace(0,3*Hs)';
026 %  s = linspace(0,3*5/4*Hs/Tz^2)';
027 %  f = bmr00pdf2(h,s,Hs,Tz);
028 %  pdfplot(f)
029 %
030 % See also mk87pdf2
031
032 % Reference
033 %  Brodtkorb, P.A. and Myrhaug, D. and Rue, H. (2000)
034 %  "Joint Distributions of Wave Height and Wave Steepness Parameters",
035 % In Proc. 27'th Int. Conf. on Coastal Eng., ICCE, Sydney, Australia },
036 %  vol. 1, pp. 545--558, Paper No. 162
037
038 % By pab 15 July 2004
039
040 error(nargchk(3,5,nargin))
041 if nargin < 5|isempty(normalizedInput), normalizedInput = 0; end
042 if nargin < 4|isempty(Tz),  Tz = 8; end
043 if nargin < 3|isempty(Hs),  Hs = 6; end
044
045 p     = createpdf(2);
046
047 [X,Y] = meshgrid(Scf,Hd);
048 p.f   = bmr00pdf(Y,X,Hs,Tz,0,normalizedInput);
049 p.x{1}=Scf(:);
050 p.x{2}=Hd(:);
051 p.labx{1}='Crest front steepness';
052 p.labx{2}='Wave height [m]';
053
054 p.title='Brodtkorb et.al. (2000) density of crest front steepness and wave height.';
055
056 [p.cl p.pl]=qlevels(p.f,[10:20:90 95 99 99.9]);
057
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group