WAFO. Description of mk87pdf2
Home > wafo > wavemodels > mk87pdf2.m
mk87pdf2
PURPOSE
Myrhaug and Kjeldsen (1987) joint (Scf,Hd) PDF.
SYNOPSIS
p = mk87pdf2(Hd,Scf,Hs,Tz)
DESCRIPTION
 MK87PDF2 Myrhaug and Kjeldsen (1987) joint (Scf,Hd) PDF.
  CALL:  f = mk87pdf2(Hd,Scf,Hs,Tz)
     f  = pdf structure evaluated at meshgrid(Scf,Hd)
    Hd  = zero down crossing wave height
    Scf = crest front steepness
    Hs  = significant wave height.
    Tz  = average zero down crossing period.
  MK87PDF2 returns the joint PDF of (Scf, Hd) given Hs and Tz,
  i.e., crest front steepness (2*pi*Ac/(g*Td*Tcf)) and wave height, given
  the seastate. The root mean square values of Hd and Scf (Hrms,Erms) are
  related to the significant waveheight and the average zero down
  crossing period by:
              Hrms = 0.715*Hs;
              Erms = 0.0202+0.826*Hs/(Tz^2);
  Example:
   Hs = 7;Tz=10;
   h = linspace(0,3*Hs)';
   s = linspace(0,3*Hs/Tz^2)';
   f = mk87pdf2(h,s,Hs,Tz);
   pdfplot(f)
  See also  mk87pdf, createpdf
CROSS-REFERENCE INFORMATION
This function calls:
createpdf
PDF class constructor
mk87pdf
Myrhaug and Kjeldsen (1987) joint (Scf,Hd) PDF.
qlevels
Calculates quantile levels which encloses P% of PDF
error
Display message and abort function.
meshgrid
X and Y arrays for 3-D plots.
This function is called by:
SOURCE CODE
001 function p = mk87pdf2(Hd,Scf,Hs,Tz)
002 %MK87PDF2 Myrhaug and Kjeldsen (1987) joint (Scf,Hd) PDF.
003 %
004 % CALL:  f = mk87pdf2(Hd,Scf,Hs,Tz)
005 %
006 %    f  = pdf structure evaluated at meshgrid(Scf,Hd)
007 %   Hd  = zero down crossing wave height
008 %   Scf = crest front steepness
009 %   Hs  = significant wave height.
010 %   Tz  = average zero down crossing period.
011 %
012 % MK87PDF2 returns the joint PDF of (Scf, Hd) given Hs and Tz,
013 % i.e., crest front steepness (2*pi*Ac/(g*Td*Tcf)) and wave height, given
014 % the seastate. The root mean square values of Hd and Scf (Hrms,Erms) are
015 % related to the significant waveheight and the average zero down
016 % crossing period by:
017 %             Hrms = 0.715*Hs;
018 %             Erms = 0.0202+0.826*Hs/(Tz^2);
019 %
020 % Example:
021 %  Hs = 7;Tz=10;
022 %  h = linspace(0,3*Hs)';
023 %  s = linspace(0,3*Hs/Tz^2)';
024 %  f = mk87pdf2(h,s,Hs,Tz);
025 %  pdfplot(f)
026 %
027 % See also  mk87pdf, createpdf
028
029 %   References:
030 %   Myrhaug, D. and Kjelsen S.P. (1987)
031 %  'Prediction of occurences of steep and high waves in deep water'.
032 %   Journal of waterway, Port, Coastal and Ocean Engineers, Vol. 113, pp 122--138
033 %
034 %   Myrhaug & Dahle (1984)
035 %   'Parametric modelling of joint probability density
036 %   distributions for steepness and asymmetry in deep water waves'
037 %
038
039 % tested on: matlab 5.1
040 % history:
041 % revised pab 09.08.2003
042 % Changed input + updated help header
043 % revised pab 01.04.2001
044 % -added example
045 % revised pab 08.02.2000
046 %  -
047 % by  Per A. Brodtkorb 1998
048
049 error(nargchk(3,4,nargin))
050
051 if nargin < 4|isempty(Tz),  Tz = 8; end
052 if nargin < 3|isempty(Hs),  Hs = 6; end
053
054 p     = createpdf(2);
055
056 [X,Y] = meshgrid(Scf,Hd);
057 p.f   = mk87pdf(Y,X,Hs,Tz);
058 p.x{1}=Scf(:);
059 p.x{2}=Hd(:);
060 p.labx{1}='Crest front steepness';
061 p.labx{2}='Wave height [m]';
062
063 p.title='Myrhaug and Kjeldsen (1987) density of crest front steepness and wave height.';
064
065 [p.cl p.pl]=qlevels(p.f,[10:20:90 95 99 99.9]);
066
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group