WAFO. Description of createpdf
Home > wafo > trgauss > createpdf.m
createpdf
PURPOSE
PDF class constructor
SYNOPSIS
f=createpdf(ndim)
DESCRIPTION
  CREATEPDF PDF class constructor
  CALL:  f=createpdf(ndim)
   creates a struct with the following fields
       f.f      = pdf (ndim-dimensional matrix)
       f.x      = cellarray of vectors of lags in ndim dimensions (ndim cells)
       f.labx   = cellarray of strings of label strings (ndim cells)
       f.title  = title string
       f.note   = note string
       f.date   = creation date and time
       ndim     = # dimensions (default 1)
   Examples:   f = createpdf(2) gives the structure
         f: []
         x: {2x1 cell}
      labx: {2x1 cell}
     title: []
      note: []
      date: '16-Oct-1999 16:56:54'
  See also  datastructures, pdfplot, createcov
CROSS-REFERENCE INFORMATION
This function calls:
cell
Create cell array.
datestr
String representation of date.
now
Current date and time as date number.
struct
Create or convert to structure array.
This function is called by:
b04jpdf2
Brodtkorb (2004) joint (Scf,Hd) PDF from Japan Sea.
b04pdf2
Brodtkorb (2004) joint (Scf,Hd) PDF of laboratory data.
bmr00pdf2
Brodtkorb et.al (2000) joint (Scf,Hd) PDF from North Sea.
cav76pdf
Cavanie et al. (1976) approximation of the density (Tc,Ac)
chitwo2lc_sp
Saddlepoint approximation of the crossing intensity for the noncentral Chi^2 process
dist2dpdf2
Joint 2D PDF computed as f(x1|X2=x2)*f(x2)
jhsnlpdf2
Joint (Scf,Hd) PDF for non-linear waves with a JONSWAP spectra.
jhspdf2
Joint (Scf,Hd) PDF for linear waves with a JONSWAP spectrum.
jhvnlpdf
Joint (Vcf,Hd) PDF for linear waves with a JONSWAP spectrum.
jhvnlpdf2
Joint (Vcf,Hd) PDF for non-linear waves with a JONSWAP spectrum.
jhvpdf
Joint (Vcf,Hd) PDF for linear waves with a JONSWAP spectrum.
jhvpdf2
Joint (Vcf,Hd) PDF for linear waves with a JONSWAP spectrum.
kde
Kernel Density Estimator.
kdebin
Binned Kernel Density Estimator.
lh83pdf
Longuet-Higgins (1983) approximation of the density (Tc,Ac)
mdist2dpdf2
Joint 2D PDF due to Plackett given as f{x1}*f{x2}*G(x1,x2;Psi).
mk87pdf2
Myrhaug and Kjeldsen (1987) joint (Scf,Hd) PDF.
ohhspdf
Joint (Scf,Hd) PDF for linear waves with Ochi-Hubble spectra.
ohhspdf2
Joint (Scf,Hd) PDF for linear waves with Ochi-Hubble spectra.
ohhsspdf
Joint (Scf,Hd) PDF linear waves in space with Ochi-Hubble spectra.
ohhsspdf2
Joint (Scf,Hd) PDF linear waves in space with Ochi-Hubble spectra.
ohhvpdf
Joint (Vcf,Hd) PDF for lineare waves with Ochi-Hubble spectra.
spec2AcAt
Evaluates survival function R(h1,h2)=P(Ac>h1,At>h2).
spec2Acdf
Evaluates cdf of crests P(Ac<=h) or troughs P(At<=h).
spec2cmat
Joint intensity matrix for cycles (max,min)-, rainflow- and (crest,trough)
spec2mmtpdf
Calculates joint density of Maximum, minimum and period.
spec2tccpdf
Evaluates densities of wave period Tcc, wave lenght Lcc.
spec2thpdf
Joint density of amplitude and period/wave-length characteristics
spec2tpdf
Evaluates densities for crest-,trough-period, length.
spec2tpdf2
Evaluates densities for various wave periods or wave lengths
specq2lc
Saddlepoint approximation of the crossing intensity for the quadratic sea.
thsnlpdf2
Joint (Scf,Hd) PDF for nonlinear waves with Torsethaugen spectra.
thspdf
Joint (Scf,Hd) PDF for linear waves with Torsethaugen spectra.
thspdf2
Joint (Scf,Hd) PDF for linear waves with Torsethaugen spectra.
thsspdf
Joint (Scf,Hd) PDF for linear waves in space with Torsethaugen spectra.
thsspdf2
Joint (Scf,Hd) PDF for linear waves in space with Torsethaugen spectra.
thvpdf
Joint (Vcf,Hd) PDF for linear waves with Torsethaugen spectra.
thvpdf2
Joint (Vcf,Hd) PDF for linear waves with Torsethaugen spectra.
trraylpdf
Calculates transformed Rayleigh approximation for amplitudes
weib2dpdf2
Joint 2D Weibull probability density function
SOURCE CODE
001 function f=createpdf(ndim)
002 % CREATEPDF PDF class constructor
003 %
004 % CALL:  f=createpdf(ndim)
005 %
006 %  creates a struct with the following fields
007 %
008 %      f.f      = pdf (ndim-dimensional matrix)
009 %      f.x      = cellarray of vectors of lags in ndim dimensions (ndim cells)
010 %      f.labx   = cellarray of strings of label strings (ndim cells)
011 %      f.title  = title string
012 %      f.note   = note string
013 %      f.date   = creation date and time
014 %
015 %      ndim     = # dimensions (default 1)
016 %
017 %  Examples:   f = createpdf(2) gives the structure
018 %        f: []
019 %        x: {2x1 cell}
020 %     labx: {2x1 cell}
021 %    title: []
022 %     note: []
023 %     date: '16-Oct-1999 16:56:54'
024 %
025 % See also  datastructures, pdfplot, createcov
026
027 %Tested on: Matlab 5.3
028 %History:
029 % revised es 25.10.1999 help and cosmetics
030 % revised pab 16.10.1999
031 % changed .xi and .labxi to .x and .labx cellarrays for
032 %      faster computation and easier access
033 % by pab 16.09.99
034
035
036 if nargin<1|isempty(ndim)
037  ndim=1;
038 end
039
040 f=struct('f',[]);
041 f.x=cell(ndim,1);
042 f.labx=cell(ndim,1);
043 f.title=[];
044 f.note=[];
045 f.date=datestr(now);
046
047
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group