WAFO. Description of dat2gaus
Home > wafo > trgauss > dat2gaus.m
dat2gaus
PURPOSE
Transforms x using the transformation g.
SYNOPSIS
xx = dat2gaus(x,g)
DESCRIPTION
  DAT2GAUS Transforms  x  using the transformation  g.
   CALL: xx = dat2gaus(x,g);
         x  = input data with time in first column and values in second.
         g  = transform function, xx=g(x).
         xx = transformed data, xx=g(x).
   See also  gaus2dat  and  tranproc.
CROSS-REFERENCE INFORMATION
This function calls:
tranproc
Transforms process X and up to four derivatives
This function is called by:
Chapter2
% CHAPTER2 Modelling random loads and stochastic waves
dat2spec2
Estimate one-sided spectral density, version 2.
reconstruct
reconstruct the spurious/missing points of timeseries
spec2AcAt
Evaluates survival function R(h1,h2)=P(Ac>h1,At>h2).
spec2Acdf
Evaluates cdf of crests P(Ac<=h) or troughs P(At<=h).
spec2cmat
Joint intensity matrix for cycles (max,min)-, rainflow- and (crest,trough)
spec2mmtpdf
Calculates joint density of Maximum, minimum and period.
spec2tccpdf
Evaluates densities of wave period Tcc, wave lenght Lcc.
spec2thpdf
Joint density of amplitude and period/wave-length characteristics
spec2tpdf
Evaluates densities for crest-,trough-period, length.
spec2tpdf2
Evaluates densities for various wave periods or wave lengths
SOURCE CODE
01 function xx = dat2gaus(x,g)
02 % DAT2GAUS Transforms  x  using the transformation  g.
03 %
04 %  CALL: xx = dat2gaus(x,g);
05 %
06 %        x  = input data with time in first column and values in second.
07 %        g  = transform function, xx=g(x).
08 %        xx = transformed data, xx=g(x).
09 %
10 %  See also  gaus2dat  and  tranproc.
11
12 xx=[x(:,1), tranproc(x(:,2:size(x,2)),g)];
13
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group