WAFO. Description of trunmak
Home > wafo > trgauss > trunmak.m
trunmak
PURPOSE
Split a transformation object into its pieces.
SYNOPSIS
[tr,ma,sa, form,not,dat] = trunmak(tro)
DESCRIPTION
 TRUNMAK Split a transformation object into its pieces.
  CALL:  [tr,ma,sa,form,note,date] = trunmak(tro);
   tro   = Transformation object
   tr    = Two column table [x g(x)] or a pp-object giving the transformation.
   ma,sa = mean and standard deviation of the process.
   form  = string identifying which form the transformation is
           given as: 'pp' or 'table'.
   note  = memorandum note
   date  = date of creation
  See also  trmak
CROSS-REFERENCE INFORMATION
This function calls:
class
Create object or return object class.
error
Display message and abort function.
This function is called by:
trplot
Plots transformation, g, eg. estimated with dat2tr.
SOURCE CODE
001 function [tr,ma,sa, form,not,dat] = trunmak(tro)
002 %TRUNMAK Split a transformation object into its pieces.
003 %
004 % CALL:  [tr,ma,sa,form,note,date] = trunmak(tro);
005 %
006 %  tro   = Transformation object
007 %  tr    = Two column table [x g(x)] or a pp-object giving the transformation.
008 %  ma,sa = mean and standard deviation of the process.
009 %  form  = string identifying which form the transformation is
010 %          given as: 'pp' or 'table'.
011 %  note  = memorandum note
012 %  date  = date of creation
013 %
014 %
015 % See also  trmak
016
017
018 % TODO % This is not complete.
019
020 error(nargchk(1,1,nargin))
021 switch class(tro),
022  case 'struct',
023   %OK
024  otherwise
025   error('This is not a transformation object!')
026 end
027
028 form = tro.form;
029 tr  = tro.tr;   % Transformation
030 ma  = tro.mean; % mean
031 sa  = tro.std;  % standard deviation
032 not = tro.note;
033 dat = tro.date;
034
035
036
037
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group