WAFO. Description of range
Home > wafo > wstats > range.m
range
PURPOSE
Calculates the difference between the maximum and minimum values.
SYNOPSIS
y = range(x)
DESCRIPTION
 RANGE  Calculates the difference between the maximum and minimum values.
  CALL: r = range(x)
    r =  max(x) - min(x), i.e. a scalar or vector giving the range of x
    x = vector or matrix
  Example:
    x=wexprnd(5,1,10)
    [min(x) max(x) range(x)]
  See also  max, min, iqr
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
dist2dcdfplot
Plot conditional empirical CDF of X1 given X2=x2
dist2dfit
Parameter estimates for DIST2D data.
dist2dstatplot
Computes and plots the conditional mean and standard deviation
findpeaks
find peaks of vector or matrix possibly rainflow filtered
jhvnlpdf
Joint (Vcf,Hd) PDF for linear waves with a JONSWAP spectrum.
jhvpdf
Joint (Vcf,Hd) PDF for linear waves with a JONSWAP spectrum.
mdist2dcdfplot
Plot conditional empirical CDF of X1 given X2=x2
mdist2dstatplot
Computes and plots the conditional mean and standard deviation.
nplot
Normal probability plot of effects
ohhspdf
Joint (Scf,Hd) PDF for linear waves with Ochi-Hubble spectra.
ohhsspdf
Joint (Scf,Hd) PDF linear waves in space with Ochi-Hubble spectra.
ohhvpdf
Joint (Vcf,Hd) PDF for lineare waves with Ochi-Hubble spectra.
pdfplot
Plot contents of pdf structures
thspdf
Joint (Scf,Hd) PDF for linear waves with Torsethaugen spectra.
thspdf2
Joint (Scf,Hd) PDF for linear waves with Torsethaugen spectra.
thsspdf
Joint (Scf,Hd) PDF for linear waves in space with Torsethaugen spectra.
thvpdf
Joint (Vcf,Hd) PDF for linear waves with Torsethaugen spectra.
weib2dcdfplot
Plot conditional empirical CDF of X1 given X2=x2
weib2dstatplot
Computes and plots the conditional mean and standard deviation
SOURCE CODE
01 function y = range(x)
02 %RANGE  Calculates the difference between the maximum and minimum values.
03 %
04 % CALL: r = range(x)
05 %
06 %   r =  max(x) - min(x), i.e. a scalar or vector giving the range of x
07 %   x = vector or matrix
08 %
09 % Example:
10 %   x=wexprnd(5,1,10)
11 %   [min(x) max(x) range(x)]
12 %
13 % See also  max, min, iqr
14
15 % By pab 06.02.2000
16
17 y = max(x) - min(x);
18
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group