WAFO. Description of weib2dpdf2
Home > wafo > wstats > weib2dpdf2.m
weib2dpdf2
PURPOSE
Joint 2D Weibull probability density function
SYNOPSIS
y = weib2dpdf2(v1,h1,phat)
DESCRIPTION
 WEIB2DPDF2 Joint 2D Weibull probability density function
   CALL:  f = weib2dpdf2(x1,x2,phat);
       f  = PDF struct with the following fields:
            f = PDF evaluated at meshgrid(x1,x2)
         x = {x1,x2} (i.e., cellarray containing x1 and x2)
   x1,x2  = vectors of evaluation points
     phat = [A1 B1 A2 B2 C12], the parameters of the distribution
  Example:
     x1=linspace(0,8)';
     phat=[2 2 2 2 .9];
     f = weib2dpdf2(x1,x1,phat);
     pdfplot(f);
  See also  weib2dfit, weib2dpdf
CROSS-REFERENCE INFORMATION
This function calls:
createpdf
PDF class constructor
qlevels
Calculates quantile levels which encloses P% of PDF
weib2dpdf
2D Weibull probability density function (pdf).
error
Display message and abort function.
meshgrid
X and Y arrays for 3-D plots.
This function is called by:
SOURCE CODE
001 function y = weib2dpdf2(v1,h1,phat)
002 %WEIB2DPDF2 Joint 2D Weibull probability density function
003 %
004 %  CALL:  f = weib2dpdf2(x1,x2,phat);
005 %
006 %      f  = PDF struct with the following fields:
007 %           f = PDF evaluated at meshgrid(x1,x2)
008 %        x = {x1,x2} (i.e., cellarray containing x1 and x2)
009 %  x1,x2  = vectors of evaluation points
010 %    phat = [A1 B1 A2 B2 C12], the parameters of the distribution
011 %
012 % Example:
013 %    x1=linspace(0,8)';
014 %    phat=[2 2 2 2 .9];
015 %    f = weib2dpdf2(x1,x1,phat);
016 %    pdfplot(f);
017 %
018 % See also  weib2dfit, weib2dpdf
019
020 %tested on: matlab 5.2
021 % history:
022 %  Per A. Brodtkorb 28.10.00
023
024 error(nargchk(3,3,nargin))
025
026 y=createpdf(2);
027 [X1 X2]=meshgrid(v1,h1);
028 y.f=  weib2dpdf(X1,X2,phat);
029 y.x{1}=v1(:);
030 y.x{2}=h1(:);
031 [y.cl y.pl]=qlevels(y.f);
032 y.note='2D Weibull';
033 y.phat=phat;
034
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group