WAFO. Description of wgamcdf
Home > wafo > wstats > wgamcdf.m
wgamcdf
PURPOSE
Gamma cumulative distribution function
SYNOPSIS
F = wgamcdf(x,a,b);
DESCRIPTION
 WGAMCDF Gamma cumulative distribution function
  CALL:  F = wgamcdf(x,a,b);
         F = distribution function evaluated at x
         a = parameter
         b = parameter (default b=1)
  The Gamma distribution is defined by its pdf
         f(x)=x^(a-1)*exp(-x/b)/gamma(a)/b^a, a,b>0, x>=0.
  Example:
    x = linspace(0,7,200);
    p1 = wgamcdf(x,1); p2 = wgamcdf(x,2);
    plot(x,p1,x,p2)
  See also  wggamcdf
CROSS-REFERENCE INFORMATION
This function calls:
comnsize
Check if all input arguments are either scalar or of common size.
error
Display message and abort function.
gammainc
Incomplete gamma function.
nan
Not-a-Number.
This function is called by:
b04jpdf
Brodtkorb (2004) joint (Scf,Hd) PDF from Japan Sea.
b04pdf
Brodtkorb (2004) joint (Scf,Hd) PDF of laboratory data.
bmr00pdf
Brodtkorb et.al (2000) joint (Scf,Hd) PDF from North Sea.
dist2dcdf
Joint 2D CDF computed as int F(X1
dist2dfun
is an internal function to dist2dcdf dist2dprb.
mdist2dcdf
Joint 2D CDF due to Plackett
mdist2dpdf
Joint 2D PDF due to Plackett given as f{x1}*f{x2}*G(x1,x2;Psi).
thsnlpdf
Joint (Scf,Hd) PDF for nonlinear waves with Torsethaugen spectra.
thspdf
Joint (Scf,Hd) PDF for linear waves with Torsethaugen spectra.
thsspdf
Joint (Scf,Hd) PDF for linear waves in space with Torsethaugen spectra.
wgamfit
Parameter estimates for Gamma data.
wgaminv
Inverse of the Gamma distribution function
wggaminv
Inverse of the Generalized Gamma distribution function
SOURCE CODE
001 function F = wgamcdf(x,a,b);
002 %WGAMCDF Gamma cumulative distribution function
003 %
004 % CALL:  F = wgamcdf(x,a,b);
005 %
006 %        F = distribution function evaluated at x
007 %        a = parameter
008 %        b = parameter (default b=1)
009 %
010 % The Gamma distribution is defined by its pdf
011 %
012 %        f(x)=x^(a-1)*exp(-x/b)/gamma(a)/b^a, a,b>0, x>=0.
013 %
014 % Example:
015 %   x = linspace(0,7,200);
016 %   p1 = wgamcdf(x,1); p2 = wgamcdf(x,2);
017 %   plot(x,p1,x,p2)
018 %
019 % See also  wggamcdf
020
021 % Reference: Johnson, Kotz and Balakrishnan (1994)
022 % "Continuous Univariate Distributions, vol. 1", p. 494 ff
023 % Wiley
024
025 % Tested on; Matlab 5.3
026 % History:
027 % revised pab 24.10.2000
028 %  - added comnsize, nargchk
029 % added ms 26.06.2000
030 % added b parameter ms 23.08.2000
031
032
033 error(nargchk(2,3,nargin))
034
035 if nargin<3|isempty(b),  b=1; end
036
037 [errorcode x a b] = comnsize(x,a,b);
038
039 if errorcode > 0
040   error('x, a and b must be of common size or scalar.');
041 end
042 F = zeros(size(x));
043
044 ok= ((a >0) & (b> 0));
045
046
047 k=find(x > 0 & ok);
048 if any(k),
049   F(k)= gammainc(x(k)./b(k),a(k));
050 end
051
052 %   Return NaN if the arguments are outside their respective limits.
053 k3 = find(~ok);
054 if any(k3)
055   tmp = NaN;
056   F(k3) = tmp(ones(size(k3)));
057 end
058
059
060
061
062
063
064
065
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group