WAFO. Description of hos
Home > wafo > kdetools > hos.m
hos
PURPOSE
Oversmoothing Parameter.
SYNOPSIS
h=hos(A,kernel)
DESCRIPTION
 HOS Oversmoothing Parameter.
  CALL:  h = hos(data,kernel)
    h      = one dimensional maximum smoothing value for smoothing parameter
             given the data and kernel.  size 1 x D
    data   = data matrix, size N x D (D = # dimensions )
    kernel = 'epanechnikov'  - Epanechnikov kernel.
             'biweight'      - Bi-weight kernel.
             'triweight'     - Tri-weight kernel.
             'triangluar'    - Triangular kernel.
             'gaussian'      - Gaussian kernel
             'rectangular'   - Rectanguler kernel.
             'laplace'       - Laplace kernel.
             'logistic'      - Logistic kernel.
   Note that only the first 4 letters of the kernel name is needed.
  The oversmoothing or maximal smoothing principle relies on the fact
  that there is a simple upper bound for the AMISE-optimal bandwidth for
  estimation of densities with a fixed value of a particular scale
  measure. While HOS will give too large bandwidth for optimal estimation
  of a general density it provides an excellent starting point for
  subjective choice of bandwidth. A sensible strategy is to plot an
  estimate with bandwidth HOS and then sucessively look at plots based on
  convenient fractions of HOS to see what features are present in the
  data for various amount of smoothing. The relation to HNS is given by:
            HOS = HNS/0.93
   Example:
   data = wnormrnd(0, 1,20,1)
   h = hos(data,'epan');
  See also  hste, hbcv, hboot, hldpi, hlscv, hscv, hstt, kde, kdefun
CROSS-REFERENCE INFORMATION
This function calls:
hns
Normal Scale Estimate of Smoothing Parameter.
This function is called by:
hbcv
Biased Cross-Validation estimate of smoothing parameter.
hboot
Bootstrap cross-validation estimate of smoothing parameter.
hlscv
Least Squares Cross-Validation estimate of smoothing parameter
hscv
Smoothed cross-validation estimate of smoothing parameter.
SOURCE CODE
001 function h=hos(A,kernel)
002 %HOS Oversmoothing Parameter.
003 %
004 % CALL:  h = hos(data,kernel)
005 %
006 %   h      = one dimensional maximum smoothing value for smoothing parameter
007 %            given the data and kernel.  size 1 x D
008 %   data   = data matrix, size N x D (D = # dimensions)
009 %   kernel = 'epanechnikov'  - Epanechnikov kernel.
010 %            'biweight'      - Bi-weight kernel.
011 %            'triweight'     - Tri-weight kernel.
012 %            'triangluar'    - Triangular kernel.
013 %            'gaussian'      - Gaussian kernel
014 %            'rectangular'   - Rectanguler kernel.
015 %            'laplace'       - Laplace kernel.
016 %            'logistic'      - Logistic kernel.
017 %
018 %  Note that only the first 4 letters of the kernel name is needed.
019 %
020 % The oversmoothing or maximal smoothing principle relies on the fact
021 % that there is a simple upper bound for the AMISE-optimal bandwidth for
022 % estimation of densities with a fixed value of a particular scale
023 % measure. While HOS will give too large bandwidth for optimal estimation
024 % of a general density it provides an excellent starting point for
025 % subjective choice of bandwidth. A sensible strategy is to plot an
026 % estimate with bandwidth HOS and then sucessively look at plots based on
027 % convenient fractions of HOS to see what features are present in the
028 % data for various amount of smoothing. The relation to HNS is given by:
029 %
030 %           HOS = HNS/0.93
031 %
032 %  Example:
033 %  data = wnormrnd(0, 1,20,1)
034 %  h = hos(data,'epan');
035 %
036 % See also  hste, hbcv, hboot, hldpi, hlscv, hscv, hstt, kde, kdefun
037
038 % Reference:
039 %  B. W. Silverman (1986)
040 % 'Density estimation for statistics and data analysis'
041 %  Chapman and Hall, pp 43-48
042
043 %  Wand,M.P. and Jones, M.C. (1986)
044 % 'Kernel smoothing'
045 %  Chapman and Hall, pp 60--63
046
047
048 %Tested on: matlab 5.3
049 % History:
050 % revised pab feb2005
051 % -updated example + see also line
052 % revised pab 21.09.99
053 %
054 % updated string comparisons
055 % from kdetools
056
057 h=hns(A,kernel)/0.93;
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group