WAFO. Description of sensortype
Home > wafo > multidim > sensortype.m
sensortype
PURPOSE
Return sensortype name
SYNOPSIS
sensor = sensortype(sensorid)
DESCRIPTION
 SENSORTYPE Return sensortype name
   CALL:   sensor = sensortype(sensorid)
   sensorid  = integer defining the sensortype
   sensor    = string defining the sensortype
                valid options are:
    'n'    : Surface elevation              (n=Eta)  (default)
    'n_t'  : Vertical surface velocity
    'n_tt' : Vertical surface acceleration
    'n_x'  : Surface slope in x-direction
    'n_y'  : Surface slope in y-direction
    'n_xx' : Surface curvature in x-direction
    'n_yy' : Surface curvature in y-direction
    'n_xy' : Surface curvature in xy-direction
    'P'    : Pressure fluctuation about static MWL pressure
    'U'    : Water particle velocity in x-direction
    'V'    : Water particle velocity in y-direction
    'W'    : Water particle velocity in z-direction
    'U_t'  : Water particle acceleration in x-direction
    'V_t'  : Water particle acceleration in y-direction
    'W_t'  : Water particle acceleration in z-direction
    'X_p'  : Water particle displacement in x-direction from its mean position
    'Y_p'  : Water particle displacement in y-direction from its mean position
    'Z_p'  : Water particle displacement in z-direction from its mean position
  Example:
  sensortype(1:18)
  See also sensortypeid
CROSS-REFERENCE INFORMATION
This function calls:
error
Display message and abort function.
isnumeric
True for numeric arrays.
strvcat
Vertically concatenate strings.
This function is called by:
SOURCE CODE
001 function sensor = sensortype(sensorid)
002 %SENSORTYPE Return sensortype name
003 %
004 %  CALL:   sensor = sensortype(sensorid)
005 %
006 %  sensorid  = integer defining the sensortype
007 %  sensor    = string defining the sensortype
008 %               valid options are:
009 %   'n'    : Surface elevation              (n=Eta)  (default)
010 %   'n_t'  : Vertical surface velocity
011 %   'n_tt' : Vertical surface acceleration
012 %   'n_x'  : Surface slope in x-direction
013 %   'n_y'  : Surface slope in y-direction
014 %   'n_xx' : Surface curvature in x-direction
015 %   'n_yy' : Surface curvature in y-direction
016 %   'n_xy' : Surface curvature in xy-direction
017 %   'P'    : Pressure fluctuation about static MWL pressure
018 %   'U'    : Water particle velocity in x-direction
019 %   'V'    : Water particle velocity in y-direction
020 %   'W'    : Water particle velocity in z-direction
021 %   'U_t'  : Water particle acceleration in x-direction
022 %   'V_t'  : Water particle acceleration in y-direction
023 %   'W_t'  : Water particle acceleration in z-direction
024 %   'X_p'  : Water particle displacement in x-direction from its mean position
025 %   'Y_p'  : Water particle displacement in y-direction from its mean position
026 %   'Z_p'  : Water particle displacement in z-direction from its mean position
027 %
028 % Example:
029 % sensortype(1:18)
030 %
031 % See also sensortypeid
032
033
034
035 %History
036 % by pab 2005
037
038   % Note the ordering of validnames can not be changed without changing
039   % the order in functions dependent on this function
040   validNames = strvcat('n','n_t','n_tt','n_x','n_y','n_xx',...
041                        'n_yy','n_xy','p','u','v','w','u_t',....
042                        'v_t','w_t','x_p','y_p','z_p','nan');
043   N = size(validNames,1)-1;
044   if nargin<1|isempty(sensorid)
045     sensorid = 1;
046   end
047   if isnumeric(sensorid)
048     sensorid(sensorid<0 | N +1 < sensorid) = N+1;
049     sensor = validNames(sensorid,:);
050   else
051     error('Input must be an integer!')
052   end
053   return
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group