WAFO. Description of getjonswappeakedness
Home > wafo > spec > getjonswappeakedness.m
getjonswappeakedness
PURPOSE
Peakedness factor Gamma given Hm0 and Tp for JONSWAP
SYNOPSIS
gam = getjonswappeakedness(Hm0,Tp)
DESCRIPTION
 GETJONSWAPPEAKEDNESS Peakedness factor Gamma given Hm0 and Tp for JONSWAP
   CALL: Gamma =  getJonswapPeakedness(Hm0,Tp);
  Hm0   = significant wave height [m].
  Tp    = peak period [s]
  gamma = Peakedness parameter of the JONSWAP spectrum
   GETJONSWAPPEAKEDNESS relate GAMMA to Hm0 and Tp.
   A standard value for GAMMA is 3.3. However, a more correct approach is
   to relate GAMMA to Hm0 and Tp:
         D = 0.036-0.0056*Tp/sqrt(Hm0);
         gamma = exp(3.484*(1-0.1975*D*Tp^4/(Hm0^2)));
   This parameterization is based on qualitative considerations of deep water
   wave data from the North Sea, see Torsethaugen et. al. (1984)
   Here GAMMA is limited to 1..7.
   NOTE: The size of GAMMA is the common size of Hm0 and Tp.
  Example
  Hm0 = linspace(1,20);
  Tp = Hm0;
  [T,H] = meshgrid(Tp,Hm0);
  gam = getjonswappeakedness(H,T);
  contourf(Tp,Hm0,gam,1:7),fcolorbar(1:7)
  Hm0 = 1:10;
  Tp  = linspace(2,16);
  [T,H] = meshgrid(Tp,Hm0);
  gam =  getjonswappeakedness(H,T);
  plot(Tp,gam)
  xlabel('Tp [s]')
  ylabel('Peakedness parameter')
  See also jonswap
CROSS-REFERENCE INFORMATION
This function calls:
comnsize
Check if all input arguments are either scalar or of common size.
error
Display message and abort function.
This function is called by:
jhnlwparfun
Wave height, Hd, distribution parameters for Stokes waves with Jonswap spectrum.
jhscdf
Joint (Scf,Hd) CDF for linear waves with a JONSWAP spectrum.
jhsnlcdf
Joint (Scf,Hd) CDF for non-linear waves with JONSWAP spectrum.
jhsnlpdf
Joint (Scf,Hd) PDF for nonlinear waves with a JONSWAP spectra.
jhsnlpdf2
Joint (Scf,Hd) PDF for non-linear waves with a JONSWAP spectra.
jhspdf
Joint (Scf,Hd) PDF for linear waves with JONSWAP spectra.
jhspdf2
Joint (Scf,Hd) PDF for linear waves with a JONSWAP spectrum.
jhvcdf
Joint (Vcf,Hd) CDF for linear waves with JONSWAP spectrum.
jhvnlcdf
Joint (Vcf,Hd) CDF for non-linear waves with JONSWAP spectrum.
jhvnlpdf
Joint (Vcf,Hd) PDF for linear waves with a JONSWAP spectrum.
jhvnlpdf2
Joint (Vcf,Hd) PDF for non-linear waves with a JONSWAP spectrum.
jhvpdf
Joint (Vcf,Hd) PDF for linear waves with a JONSWAP spectrum.
jhvpdf2
Joint (Vcf,Hd) PDF for linear waves with a JONSWAP spectrum.
jhwparfun
Wave height, Hd, distribution parameters for Jonswap spectrum.
jonswap
Calculates (and plots) a JONSWAP spectral density
SOURCE CODE
001 function gam = getjonswappeakedness(Hm0,Tp)
002 %GETJONSWAPPEAKEDNESS Peakedness factor Gamma given Hm0 and Tp for JONSWAP
003 %
004 %  CALL: Gamma =  getJonswapPeakedness(Hm0,Tp);
005 %
006 % Hm0   = significant wave height [m].
007 % Tp    = peak period [s]
008 % gamma = Peakedness parameter of the JONSWAP spectrum
009 %
010 %  GETJONSWAPPEAKEDNESS relate GAMMA to Hm0 and Tp.
011 %  A standard value for GAMMA is 3.3. However, a more correct approach is
012 %  to relate GAMMA to Hm0 and Tp:
013 %        D = 0.036-0.0056*Tp/sqrt(Hm0);
014 %        gamma = exp(3.484*(1-0.1975*D*Tp^4/(Hm0^2)));
015 %  This parameterization is based on qualitative considerations of deep water
016 %  wave data from the North Sea, see Torsethaugen et. al. (1984)
017 %  Here GAMMA is limited to 1..7.
018 %
019 %  NOTE: The size of GAMMA is the common size of Hm0 and Tp.
020 %
021 % Example
022 % Hm0 = linspace(1,20);
023 % Tp = Hm0;
024 % [T,H] = meshgrid(Tp,Hm0);
025 % gam = getjonswappeakedness(H,T);
026 % contourf(Tp,Hm0,gam,1:7),fcolorbar(1:7)
027 %
028 % Hm0 = 1:10;
029 % Tp  = linspace(2,16);
030 % [T,H] = meshgrid(Tp,Hm0);
031 % gam =  getjonswappeakedness(H,T);
032 % plot(Tp,gam)
033 % xlabel('Tp [s]')
034 % ylabel('Peakedness parameter')
035 %
036 % See also jonswap
037
038 % Tested on matlab 6.1
039 %History
040 % revised pab 13april2004
041 % -made sure gamma is 1 if Tp/sqrt(Hm0) > 5.1429
042 % by pab 11Jan2004
043
044   error(nargchk(2,2,nargin))
045   [errorcode,Hm0,Tp] = comnsize(Hm0,Tp);
046   if errorcode > 0
047     error('Requires non-scalar arguments to match in size.');
048   end
049   x   = Tp./sqrt(Hm0);
050
051   gam = ones(size(x));
052
053   k1 = find(x<=5.14285714285714);
054   if any(k1), %limiting gamma to [1 7]
055     D       = 0.036-0.0056*x(k1); % approx 5.061*Hm0^2/Tp^4*(1-0.287*log(gam));
056     gam(k1) = min(exp(3.484*(1-0.1975*D.*x(k1).^4)),7); % gamma
057   end
058   return
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group