WAFO. Description of gravity
Home > wafo > misc > gravity.m
gravity
PURPOSE
returns the constant acceleration of gravity
SYNOPSIS
g=gravity(phi)
DESCRIPTION
  GRAVITY  returns the constant acceleration of gravity
   CALL:  g = gravity(phi);
    g   =  acceleration of gravity in m/s^2
    phi =  latitude in degrees (default 45 degrees)
   GRAVITY calculates the acceleration of gravity
   using the international gravitational formulae:
    g = 9.78049*(1+0.0052884*sin(phi).^2-0.0000059*sin(2*phi).^2);
   Edit GRAVITY.M to change default value for PHI.
  Example:%
     g = gravity
  See also wdensity
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
dat2steep
Extracts waveheights and steepnesses from data.
dir2enc
Transform a dir. spectrum to an encountered. (Used in spec2spec)
dir2k1d
Transforms directional spectrum to wavenumber spectrum.
dirsp2chitwo
gives parameters in non-central CHI-TWO process for directional Stokes waves.
dspec2dcov
Return covariance function given a directional spectrum
ewwdir
Computes values of the quadratic transfer function E, for quadratic sea
jonswap
Calculates (and plots) a JONSWAP spectral density
k2w
Translates from wave number to frequency
phi1
factor for transforming spectra to finite water depth spectra
recinit
setup all global variables of the RECDEMO
scalespec
Scale spectral density so that the moments equals m0,m2.
seasim
Spectral simulation of a Gaussian sea, 2D (x,t) or 3D (x,y,t)
spa2time
Transform of spectrum from wave no. to frequency (used in spec2spec)
spec2char
Evaluates spectral characteristics and their covariance
spec2linspec
Separates the linear component of the Spectrum
spec2mom
Calculates spectral moments from spectrum
spec2nlsdat
Simulates a Randomized 2nd order non-linear wave X(t)
spec2skew
Estimates the moments of 2'nd order non-linear waves
specoptset
Create or alter SPECTRUM OPTIONS structure.
specq2lc
Saddlepoint approximation of the crossing intensity for the quadratic sea.
testbuoy
creates a test case for a buoy measurement
testmeasurements
Creates a test case for measurement time series
testsurf
creates a test case for a surface elevation measurement
time2spa
Transform of spectrum from frequency to wave no. (used in spec2spec)
tmaspec
Calculates a JONSWAP spectral density for finite water depth
torsethaugen
Calculates a double peaked (swell + wind) spectrum
tran
Computes transfer functions based on linear wave theory
w2k
Translates from frequency to wave number
wnormspec
Normalize a spectral density such that m0=m2=1
SOURCE CODE
001 function g=gravity(phi)
002 % GRAVITY  returns the constant acceleration of gravity
003 %
004 %  CALL:  g = gravity(phi);
005 %
006 %   g   =  acceleration of gravity in m/s^2
007 %   phi =  latitude in degrees (default 45 degrees)
008 %
009 %  GRAVITY calculates the acceleration of gravity
010 %  using the international gravitational formulae:
011 %
012 %   g = 9.78049*(1+0.0052884*sin(phi).^2-0.0000059*sin(2*phi).^2);
013 %
014 %  Edit GRAVITY.M to change default value for PHI.
015 %
016 % Example:%
017 %    g = gravity
018 % See also wdensity
019
020 % References:
021 % Irgens, Fridtjov (1987)
022 % "Formelsamling i mekanikk:
023 % statikk, fasthetslære, dynamikk fluidmekanikk"
024 % tapir forlag, University of Trondheim , ISBN 82-519-0786-1, pp 19
025
026 % history
027 % revised pab 06.01.2000
028 %  - added phi and international gravitational formulae.
029 %  - updated documentation
030
031 if nargin<1 |isempty(phi)
032   phi=45;
033 end
034 phi=phi*pi/180; % change from degrees to radians
035
036 g=9.78049*(1+0.0052884*sin(phi).^2-0.0000059*sin(2*phi).^2);
037 %g=9.80665000000;
038
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group