WAFO. Description of levels
Home > wafo > misc > levels.m
levels
PURPOSE
Calculates discrete levels given the parameter matrix.
SYNOPSIS
l=levels(param)
DESCRIPTION
 LEVELS Calculates discrete levels given the parameter matrix.
   CALL: ui = levels(param);
         ui    = the discrete levels.
         param = the parameter matrix = [u_min u_max num_levels].
  Example:%
  param=[2 3.2 4]; levels(param)
CROSS-REFERENCE INFORMATION
This function calls:
linspace
Linearly spaced vector.
This function is called by:
cav76pdf
Cavanie et al. (1976) approximation of the density (Tc,Ac)
cc2cmat
Calculates the cycle count matrix from a cycle count.
cdf2tr
Estimate transformation, g, from observed CDF.
Chapter4
% CHAPTER4 contains the commands used in Chapter 4 of the tutorial
cmat2amp
Calculates a histogram of amplitudes from a cycle matrix.
cmat2dmat
Computes the (Palmgren-Miner) damage matrix from a cycle matrix.
cmat2extralc
Extrapolate level crossing spectrum
cmat2lc
Calculates the level crossings from a cycle matrix.
cocc
Plots cycles as points together with isolines of a cycle matrix.
dat2dtp
The sequence of discretized turning points from a signal.
dat2rfm
Calculates the rainflow matrix from a time signal.
dat2tr
Estimate transformation, g, from data.
itmkurs_lab2
Script to computer exercises 2
itmkurs_lab3
Script to computer exercises 3
itmkurs_lab4
Script to computer exercises 4
lc2tr
Estimate transformation, g, from observed crossing intensity.
lc2tr2
Estimate transformation, g, from observed crossing intensity, version2.
lh83pdf
Longuet-Higgins (1983) approximation of the density (Tc,Ac)
load2ud
Calculates the number of up/downcrossings of a load.
mc2rfc
Calculates a rainflow matrix given a Markov chain with kernel f_xy;
mctp2tc
Frequencies of upcrossing troughs and crests using Markov chain of turning points.
mktestmat
Makes test matrices for min-max (and max-min) matrices.
nt2lc
Calculates the level crossings from a cycle matrix.
rfcdemo1
Demo for switching AR(1)-processes.
rfcdemo2
Rainflow matrix for Switching Markov Chains of Turning Points.
rfmextrapolate
Extrapolates a rainflow matrix.
scalemat
Scale and translate a cycle matrix.
spec2AcAt
Evaluates survival function R(h1,h2)=P(Ac>h1,At>h2).
spec2Acdf
Evaluates cdf of crests P(Ac<=h) or troughs P(At<=h).
spec2cmat
Joint intensity matrix for cycles (max,min)-, rainflow- and (crest,trough)
spec2mmtpdf
Calculates joint density of Maximum, minimum and period.
spec2tccpdf
Evaluates densities of wave period Tcc, wave lenght Lcc.
spec2thpdf
Joint density of amplitude and period/wave-length characteristics
spec2tpdf
Evaluates densities for crest-,trough-period, length.
spec2tpdf2
Evaluates densities for various wave periods or wave lengths
test_cycles
Quick test of the routines in module 'cycles'
test_markov
Quick test of the routines in module 'markov'
SOURCE CODE
01 function l=levels(param)
02 %LEVELS Calculates discrete levels given the parameter matrix.
03 %
04 %  CALL: ui = levels(param);
05 %
06 %        ui    = the discrete levels.
07 %        param = the parameter matrix = [u_min u_max num_levels].
08 % Example:%
09 %
10 % param=[2 3.2 4]; levels(param)
11
12 l=linspace(param(1),param(2),param(3));
13
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group