WAFO. Description of waforoot
Home > wafo > waforoot.m
waforoot
PURPOSE
Root directory of WAFO installation.
SYNOPSIS
exedir=watroot;
DESCRIPTION
  WAFOROOT Root directory of WAFO installation.
  CALL:  Str = waforoot
     Str = string with the path name to the directory where the
           Wave Analysis for Fatigue and Oceanography Toolbox is installed.
   WAFOROOT is used to produce platform dependent paths
   to the various WAFO directories.
   Example:
     fullfile(waforoot,filesep, 'spec','')
     produces a full path to the <waforoot>/spec directory that
     is correct for platform it's executed on.
     See also  wafopath, wafoexepath, fullfile.
CROSS-REFERENCE INFORMATION
This function calls:
error
Display message and abort function.
findstr
Find one string within another.
lower
Convert string to lowercase.
which
Locate functions and files.
This function is called by:
initwafo
Initiation of WAFO Toolbox.
itmkurs
Initiate paths for Demo Load and Fatigue Analysis
mkcontents
Makes Contents file in current working directory.
recinit
setup all global variables of the RECDEMO
rfcdemo1
Demo for switching AR(1)-processes.
test_cycles
Quick test of the routines in module 'cycles'
wafoexepath
Returns the path to executables for the WAFO Toolbox
wafohelp
Launch HTML help for the WAFO Toolbox.
wafoinit
setup all global variables of the WAFODEMO
wafomenu
displays a user interface to the documentation files of WAFO
wafopath
Adds or removes WAFO subdirectories from the search path.
wafoversion
Wave Analysis for Fatigue and Oceanography version.
SOURCE CODE
001 function exedir=watroot;
002 % WAFOROOT Root directory of WAFO installation.
003 %
004 % CALL:  Str = waforoot
005 %
006 %    Str = string with the path name to the directory where the
007 %          Wave Analysis for Fatigue and Oceanography Toolbox is installed.
008 %
009 %  WAFOROOT is used to produce platform dependent paths
010 %  to the various WAFO directories.
011 %
012 %  Example:
013 %    fullfile(waforoot,filesep, 'spec','')
014 %
015 %    produces a full path to the <waforoot>/spec directory that
016 %    is correct for platform it's executed on.
017 %
018 %    See also  wafopath, wafoexepath, fullfile.
019
020
021 %          NOTE: User no longer has to edit this file (since v1.1.14).
022 %          It is now automatic.
023
024 % Tested on: Matlab 5.3
025 % History:
026 % revised by pab 15.09.00
027 %   - fixed bug: lower(exedir)
028 % revised by pab 11.08.99
029 %   new routine  based on old  wavepath
030
031 exedir=which('waforoot');
032 i=max(findstr(lower(exedir),'waforoot'))-2;
033 if i>0
034   exedir=exedir(1:i);
035 else
036   exedir=[];
037   disp('Cannot locate  waforoot.m')
038   disp('You must add the path to the WAFO Toolbox')
039   disp('to the Matlab-path.')
040   error('!!')
041 end
042
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group