WAFO. Description of wafoexepath
Home > wafo > wafoexepath.m
wafoexepath
PURPOSE
Returns the path to executables for the WAFO Toolbox
SYNOPSIS
p=wafoexepath;
DESCRIPTION
  WAFOEXEPATH Returns the path to executables for the WAFO Toolbox
  CALL:  Str = wafoexepath
    Str  =  a string with the path to the directory containing
            the executables for the WAFO Toolbox,
            including a terminating slash or backslash, depending
            on the system on wich Matlab is run.
            The executable files must be located in a subdirectory to
            the WAFO/exec directory, with the name given by
            "lower(computer)".
  See also  waforoot, wafopath.
CROSS-REFERENCE INFORMATION
This function calls:
waforoot
Root directory of WAFO installation.
computer
Computer type.
filesep
Directory separator for this platform.
lower
Convert string to lowercase.
This function is called by:
down2cc
Calculates the cycle count which has the highest damage
duffsim
Generates a sample path of a harmonic oscillator
rind
Computes multivariate normal expectations
spec2AcAt
Evaluates survival function R(h1,h2)=P(Ac>h1,At>h2).
spec2Acdf
Evaluates cdf of crests P(Ac<=h) or troughs P(At<=h).
spec2mmtpdf
Calculates joint density of Maximum, minimum and period.
spec2tccpdf
Evaluates densities of wave period Tcc, wave lenght Lcc.
spec2thpdf
Joint density of amplitude and period/wave-length characteristics
spec2tpdf
Evaluates densities for crest-,trough-period, length.
wminmax
Calculates joint density of minimum and following maximum
SOURCE CODE
01 function p=wafoexepath;
02 % WAFOEXEPATH Returns the path to executables for the WAFO Toolbox
03 %
04 % CALL:  Str = wafoexepath
05 %
06 %   Str  =  a string with the path to the directory containing
07 %           the executables for the WAFO Toolbox,
08 %           including a terminating slash or backslash, depending
09 %           on the system on wich Matlab is run.
10 %           The executable files must be located in a subdirectory to
11 %           the WAFO/exec directory, with the name given by
12 %           "lower(computer)".
13 %
14 % See also  waforoot, wafopath.
15
16
17 %          NOTE: User no longer has to edit this file
18 %          It is  automatic.
19
20 % Tested on: Matlab 5.3
21 % History:
22 % by by pab 11.08.99
23 %   new routine
24
25 p = [ waforoot, filesep, 'exec' filesep lower(computer) filesep];
26
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group