WAFO. Description of wafofig1
Home > wafo > papers > wafodemo > wafofig1.m
wafofig1
PURPOSE
Linear simulation from a Torsethaugen spectrum.
SYNOPSIS
wafofig1
DESCRIPTION
  WAFOFIG1  Linear simulation from a Torsethaugen spectrum.
            Use the mouse to zoom in on a specific region.
CROSS-REFERENCE INFORMATION
This function calls:
wafostamp
Prints a caption "made by WAFO" in current figure.
waveplot
Plots the surface elevation of timeseries.
clear
Clear variables and functions from memory.
num2str
Convert number to string. (Fast version)
zoom
Zoom in and out on a 2-D plot.
This function is called by:
SOURCE CODE
01 function wafofig1
02 % WAFOFIG1  Linear simulation from a Torsethaugen spectrum.
03 %           Use the mouse to zoom in on a specific region.
04 %
05
06 global  WAFOFIGNUM
07
08 if isempty(WAFOFIGNUM)
09   disp('You must start wafodemo in order to run this script')
10   clear global WAFOFIGNUM
11   return
12 end
13
14 global xt Hm0 Tp
15
16 disp(['        Hm0 = ' num2str(Hm0), '   Tp = ', num2str(Tp)])
17 waveplot(xt,'-',1,1)
18 zoom xon
19 wafostamp('Figure 1','(ER)')
20
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group