WAFO. Description of wafointro
Home > wafo > papers > wafodemo > wafointro.m
wafointro
PURPOSE
Info about WAFODEMO: WAFO - a Matlab toolbox for analysis of random waves and loads
SYNOPSIS
wafointro
DESCRIPTION
 WAFOINTRO  Info about WAFODEMO: WAFO - a Matlab toolbox for analysis of random waves and loads
  The files in this directory can reproduce the figures in the
  article of
  Brodtkorb, P.A., Johannesson, P., Lindgren, G., Rychlik, I., Ryden, J
  and Sjo, E. (2000)
  'WAFO - a Matlab toolbox for analysis of random waves and loads'
   to appear in Proceedings of 10th ISOPE Conference, Seattle
  The paper demonstrates in examples some of the capabilities of WAFO:
    - Construction of model spectra, directional model spectra with known
      spreading function
    - Simulation of transformed Gaussian processes
    - Spectral density estimation
    - Probability distributions of wave characteristics:
         1) Joint density of Vcf and Ac
         2) Joint density of Tcf and Ac given Tc=5
         3) Distribution of extremal crest
    - Fatigue, Cycles and Markov models
    (See wafomenu for numenclature and wave parameter definitions)
  See also  wafomenu, recdemo
CROSS-REFERENCE INFORMATION
This function calls:
wafointro
Info about WAFODEMO: WAFO - a Matlab toolbox for analysis of random waves and loads
help
Display help text in Command Window.
This function is called by:
wafodemo
Show WAFO figures with point and click interface
wafointro
Info about WAFODEMO: WAFO - a Matlab toolbox for analysis of random waves and loads
SOURCE CODE
001 function wafointrowafointro
002 %WAFOINTRO  Info about WAFODEMO: WAFO - a Matlab toolbox for analysis of random waves and loads
003 %
004 % The files in this directory can reproduce the figures in the
005 % article of
006 %
007 % Brodtkorb, P.A., Johannesson, P., Lindgren, G., Rychlik, I., Ryden, J
008 % and Sjo, E. (2000)
009 % 'WAFO - a Matlab toolbox for analysis of random waves and loads'
010 %  to appear in Proceedings of 10th ISOPE Conference, Seattle
011 %
012 %
013 % The paper demonstrates in examples some of the capabilities of WAFO:
014 %
015 %   - Construction of model spectra, directional model spectra with known
016 %     spreading function
017 %   - Simulation of transformed Gaussian processes
018 %   - Spectral density estimation
019 %   - Probability distributions of wave characteristics:
020 %        1) Joint density of Vcf and Ac
021 %        2) Joint density of Tcf and Ac given Tc=5
022 %        3) Distribution of extremal crest
023 %   - Fatigue, Cycles and Markov models
024 %
025 %   (See wafomenu for numenclature and wave parameter definitions)
026 %
027 % See also  wafomenu, recdemo
028
029 % TODO % Needs more details regarding what this demo is about
030
031 % Tested on: Matlab 5.2
032 % history:
033 % By pab 28.01.2000
034
035 %more on
036 help wafointro
037 %more off
038
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group