WAFO. Description of wafodemo
Home > wafo > papers > wafodemo > wafodemo.m
wafodemo
PURPOSE
Show WAFO figures with point and click interface
SYNOPSIS
wafodemo
DESCRIPTION
  WAFODEMO  Show WAFO figures with point and click interface
  CALL:    wafodemo
CROSS-REFERENCE INFORMATION
This function calls:
choices
Create a list of choices with uicontrols and callbacks.
wafointro
Info about WAFODEMO: WAFO - a Matlab toolbox for analysis of random waves and loads
clc
Clear command window.
str2mat
Form blank padded character matrix from strings.
strvcat
Vertically concatenate strings.
This function is called by:
SOURCE CODE
01 function wafodemo
02 % WAFODEMO  Show WAFO figures with point and click interface
03 %
04 % CALL:    wafodemo
05 %
06
07 % tested on: Matlab 5.2
08 % History
09 % By pab 28.01.2000
10
11
12 % TODO % update calls to spec2XXpdf programmes due to change in call
13
14 header = 'WAFO Demo';
15 labels =strvcat('Change Settings' , 'Run All Scripts' , ...
16           'Run One Script' , 'Clean Up');
17 callbacks = str2mat('wafofig(-1)', 'wafofig(-2)', ...
18              'wafofig(-3)', 'wafocleanup');
19 global WAFOFIGNUM
20 WAFOFIGNUM = 0;
21 clc;
22 wafointro
23 choices('WAFO',header,labels,callbacks);
24
25
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group