WAFO. Description of wafofig2
Home > wafo > papers > wafodemo > wafofig2.m
wafofig2
PURPOSE
Spectral densities:
SYNOPSIS
wafofig2
DESCRIPTION
  WAFOFIG2  Spectral densities:
            Original Torsethaugen spectrum (solid),
            Estimated from linear simulations (dash), and
            95% Confidence interval (dotted)
CROSS-REFERENCE INFORMATION
This function calls:
wafostamp
Prints a caption "made by WAFO" in current figure.
wspecplot
Plot a spectral density
clear
Clear variables and functions from memory.
hold
Hold current graph.
ishold
Return hold state.
This function is called by:
SOURCE CODE
01 function wafofig2
02 % WAFOFIG2  Spectral densities:
03 %           Original Torsethaugen spectrum (solid),
04 %           Estimated from linear simulations (dash), and
05 %           95% Confidence interval (dotted)
06 %
07
08 global  WAFOFIGNUM
09
10 if isempty(WAFOFIGNUM)
11   disp('You must start wafodemo in order to run this script')
12   clear global WAFOFIGNUM
13   return
14 end
15
16 global St Ste
17 wspecplot(St,1,'k-')
18 ih=ishold;
19 hold on
20 wspecplot(Ste,1,'--')
21 if ~ih, hold off, end
22 wafostamp('Figure 2','(ER)')
23
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group