WAFO. Description of hanning
Home > wafo > onedim > private > hanning.m
hanning
PURPOSE
returns the N-point Hanning window in a column vector.
SYNOPSIS
w = hanning(n,p)
DESCRIPTION
  HANNING returns the N-point Hanning window in a column vector.
   CALL: win = hanning(n)
     win = hanning window
       n = number of points
  See also bingham, parzen
CROSS-REFERENCE INFORMATION
This function calls:
bingham
returns the N-point Bingham window in a column vector.
This function is called by:
dat2spec
Estimate one-sided spectral density from data.
dat2spec2
Estimate one-sided spectral density, version 2.
SOURCE CODE
01 function w = hanning(n,p)
02 % HANNING returns the N-point Hanning window in a column vector.
03 %
04 %  CALL: win = hanning(n)
05 %
06 %    win = hanning window
07 %      n = number of points
08 %
09 % See also bingham, parzen
10
11 % Tested on: matlab 5.3
12 % History:
13 %  by Per Andreas Brodtkorb%    16.09.1999
14   w=bingham(n,1);
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group