WAFO. Description of down2cc
Home > wafo > damage > down2cc.m
down2cc
PURPOSE
Calculates the cycle count which has the highest damage
SYNOPSIS
[cc,delta] = down2cc(mu,n)
DESCRIPTION
 DOWN2CC Calculates the cycle count which has the highest damage
   given the downcrossing intensity.
  CALL:  [cc,delta] = down2cc(cross,n);
        cc    = the cycle count,
        delta = the slice distance,
        cross = a two column matrix with the levels  u  in the first
                column and the number of downcrossings/downcrossing
                intensity in the second,
        n     = the number of slice levels between 0 and maximum of
                the number of downcrossings/downcrossing intensity.
CROSS-REFERENCE INFORMATION
This function calls:
wafoexepath
Returns the path to executables for the WAFO Toolbox
delete
Delete file or graphics object.
dos
Execute DOS command and return result.
exist
Check if variables or functions are defined.
slice
Volumetric slice plot.
This function is called by:
lc2dplus
Upper bound for total damage from level crossings.
SOURCE CODE
001 function [cc,delta] = down2cc(mu,n)
002 %DOWN2CC Calculates the cycle count which has the highest damage
003 %  given the downcrossing intensity.
004 %
005 % CALL:  [cc,delta] = down2cc(cross,n);
006 %
007 %       cc    = the cycle count,
008 %       delta = the slice distance,
009 %       cross = a two column matrix with the levels  u  in the first
010 %               column and the number of downcrossings/downcrossing
011 %               intensity in the second,
012 %       n     = the number of slice levels between 0 and maximum of
013 %               the number of downcrossings/downcrossing intensity.
014
015 %  Copyright 1993, Mats Frendahl, Dept. of Math. Stat., University of Lund.
016
017 if exist('slice.dat'), delete slice.dat, end
018 if exist('crossint.dat'), delete crossint.dat, end
019
020 disp('   Writing data.')
021 fprintf('slice.dat','%4.0f\n',n)
022 fprintf('crossint.dat','%10.5f %10.5f\n',mu');
023
024 disp('   Starting Fortran executable.')
025 dos([ wafoexepath 'down2cc.exe']);
026
027 disp('   Loading data.')
028 load out.dat
029 cc=out(:,2:3);
030
031 delta=max(mu(:,2))/n;
032
033 delete slice.dat crossint.dat
034
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group