WAFO. Description of spec2dplus
Home > wafo > damage > spec2dplus.m
spec2dplus
PURPOSE
Calculates an upper bound of the damage intensity explicitly
SYNOPSIS
d = spec2dplus(S,bet)
DESCRIPTION
  SPEC2DPLUS Calculates an upper bound of the damage intensity explicitly
  CALL:  d = spec2dplus(S,bet)
         d = an upper bound of the damage intensity
         S = a spectral density (structure array)
       bet = the parameter beta
  The upper bound of the damage intensity can be calculated explicitly and is
  given by
        d^+ = 2^{3*beta/2}*sqrt(lam2)*(lam0)^{(beta-1)/2}*gamma(1+beta/2)/(2*pi)
CROSS-REFERENCE INFORMATION
This function calls:
spec2mom
Calculates spectral moments from spectrum
gamma
Gamma function.
This function is called by:
itmkurs_lab3
Script to computer exercises 3
SOURCE CODE
01 function d = spec2dplus(S,bet)
02 % SPEC2DPLUS Calculates an upper bound of the damage intensity explicitly
03 %
04 % CALL:  d = spec2dplus(S,bet)
05 %
06 %        d = an upper bound of the damage intensity
07 %
08 %        S = a spectral density (structure array)
09 %      bet = the parameter beta
10 %
11 % The upper bound of the damage intensity can be calculated explicitly and is
12 % given by
13 %
14 %       d^+ = 2^{3*beta/2}*sqrt(lam2)*(lam0)^{(beta-1)/2}*gamma(1+beta/2)/(2*pi)
15 %
16
17 % Example
18 %  S = oscspec; bet = 3:0.2:5;
19 %  dplus = spec2dplus(S,bet)
20
21 % Tested on: Matlab 5.3
22 % History:
23 % By jr 12.01.2000
24
25 lam = spec2mom(S); l0 = sqrt(lam(1));, l2 = sqrt(lam(2));
26
27 d = (2.^(bet/2)).*(l0.^(bet-1)).*gamma(bet/2+1)*l2/2/pi;
28
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group