WAFO. Description of democc_plotmat
Home > wafo > wdemos > democc_plotmat.m
democc_plotmat
PURPOSE
plots RFC and min-max counts.
SYNOPSIS
democc_plotmat(demow2,ccrfc,ccmM)
DESCRIPTION
 DEMOCC_PLOTMAT plots RFC and min-max counts.
  CALL: democc_plotmat(demow2,ccrfc,ccmM)
  Used by democc
CROSS-REFERENCE INFORMATION
This function calls:
ccplot
Plots a cycle count as a point process in the plane.
axis
Control axis scaling and appearance.
figure
Create figure window.
hold
Hold current graph.
plot
Linear plot.
subplot
Create axes in tiled positions.
title
Graph title.
This function is called by:
SOURCE CODE
01 function democc_plotmat(demow2,ccrfc,ccmM)
02 %DEMOCC_PLOTMAT plots RFC and min-max counts.
03 %
04 % CALL: democc_plotmat(demow2,ccrfc,ccmM)
05 %
06 % Used by democc
07
08 % Tested on: matlab 5.3
09 % History:
10 % Created by by PJ 10-Jan-2000
11
12 figure(demow2)
13
14 subplot(1,2,1)
15 if ~isempty(ccrfc)
16   ccplot(ccrfc),hold on
17   v=axis; plot(v(1:2),v(3:4),'--'),hold off
18 end
19 title('Rainflow cycles')
20
21 subplot(1,2,2)
22 if ~isempty(ccmM)
23   ccplot(ccmM),hold on
24   v=axis; plot(v(1:2),v(3:4),'--'),hold off
25 end
26 title('min-max cycles')
27
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group