WAFO. Description of democc_mmdef
Home > wafo > wdemos > democc_mmdef.m
democc_mmdef
PURPOSE
illustrates the definition of min-max cycles.
SYNOPSIS
ccmM=democc_mmdef(proc,tp,point,ccpt)
DESCRIPTION
 DEMOCC_MMDEF illustrates the definition of min-max cycles.
  CALL: ccmM=democc_mmdef(proc,tp,point,ccpt)
  Used by democc
CROSS-REFERENCE INFORMATION
This function calls:
democc_markmax
plots load and marks a maximum
hold
Hold current graph.
plot
Linear plot.
title
Graph title.
This function is called by:
SOURCE CODE
01 function ccmM=democc_mmdef(proc,tp,point,ccpt)
02
03 %DEMOCC_MMDEF illustrates the definition of min-max cycles.
04 %
05 % CALL: ccmM=democc_mmdef(proc,tp,point,ccpt)
06 %
07 % Used by democc
08
09 % Tested on: matlab 5.3
10 % History:
11 % Revised by PJ 10-Jan-2000
12 %   updated for WAFO
13 % Original version by Mats Frendahl
14
15 ms = 20; % markersize
16
17 democc_markmax(proc,tp,point,0);
18 hold on, title('Definition of peak-trough count')
19 plot(tp(point-1,1),tp(point-1,2),'k.','markersize',ms)
20 plot(tp(point,1),tp(point,2),'k.','markersize',ms)
21 hold off
22 if isempty(ccpt)
23    ccmM=[tp(point-1,2) tp(point,2)];
24 else
25    ccmM=[ccpt; tp(point-1,2) tp(point,2)];
26 end
27
28
29
Mathematical Statistics
Centre for Mathematical Sciences
Lund University with Lund Institute of Technology
Comments or corrections to the WAFO group